    version: "3.8"

    services:
      backend:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: backend
        env_file:
          - .env
        ports:
          - "8000:8000"
        restart: unless-stopped
        # volumes:
        #   - .:/app  # Uncomment for live development
