/**
 * The assistant markdown document of the parity fixture. One string that
 * exercises every block the two markdown renderers draw: headings h1–h6,
 * nested ordered/unordered/task lists, a table with alignment, a blockquote,
 * every inline-code class (short token, long path, URL, hex color), code
 * fences in ts/tsx/bash/json/python/diff, inline and block math, and two
 * Mermaid diagrams (flowchart + sequence).
 */

const FENCE = '```';

export const FIXTURE_MARKDOWN_DOCUMENT = [
  '# Advisory lock rollout',
  '',
  'The job queue now elects one leader per queue with a Postgres advisory lock. This note records what changed, why, and how to verify it.',
  '',
  '## Summary',
  '',
  'Workers call `pg_try_advisory_lock` on start. The worker that holds the lock drains the queue; every other worker polls every **5 s** and takes over within *one* poll interval when the leader dies. ~~Redis locks~~ are gone.',
  '',
  '### Inline code classes',
  '',
  '- Short token: `leader`',
  '- Long path: `/workspace/acme-dashboard/src/server/jobs/queue/advisory-lock-leader-election.ts`',
  '- URL: `https://www.postgresql.org/docs/current/explicit-locking.html`',
  '- Color token: `#0ea5e9`',
  '- A real link: [PostgreSQL advisory locks](https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS)',
  '',
  '#### Rollout steps',
  '',
  '1. Ship the lock helper behind `JOBS_ADVISORY_LOCK=1`.',
  '2. Enable it on one region:',
  '   - `eu-west-1` first',
  '   - `us-east-1` after 24 h',
  '3. Remove the Redis lock client.',
  '',
  '- [x] Lock helper merged',
  '- [x] Metrics dashboard updated',
  '- [ ] Redis client removed',
  '',
  '##### Numbers',
  '',
  '| Metric | Before | After | Change |',
  '| :--- | ---: | ---: | :---: |',
  '| p50 claim latency | 41 ms | 6 ms | −85% |',
  '| p99 claim latency | 820 ms | 38 ms | −95% |',
  '| Duplicate runs / day | 17 | 0 | −100% |',
  '| Lock-holder failovers | n/a | 3 | new |',
  '',
  '###### Footnote',
  '',
  '> A session-level advisory lock is released when the backend disconnects.',
  '> A worker killed between `lock` and `commit` keeps the lock until its',
  '> connection times out — **30 s** with the current pool settings.',
  '',
  '## Code',
  '',
  `${FENCE}ts`,
  "import { sql } from './db';",
  '',
  'export async function tryLead(queue: string): Promise<boolean> {',
  '  const [row] = await sql<{ locked: boolean }>`',
  '    SELECT pg_try_advisory_lock(hashtext(${queue})) AS locked',
  '  `;',
  '  return row?.locked ?? false;',
  '}',
  FENCE,
  '',
  `${FENCE}tsx`,
  "import { Badge } from '@/components/ui/badge';",
  '',
  'export function LeaderBadge({ isLeader }: { isLeader: boolean }) {',
  '  return <Badge variant={isLeader ? \'default\' : \'secondary\'}>{isLeader ? \'Leader\' : \'Follower\'}</Badge>;',
  '}',
  FENCE,
  '',
  `${FENCE}bash`,
  'JOBS_ADVISORY_LOCK=1 pnpm --filter api test -- jobs/queue',
  "psql \"$DATABASE_URL\" -c 'SELECT locktype, objid, pid FROM pg_locks WHERE locktype = $$advisory$$;'",
  FENCE,
  '',
  `${FENCE}json`,
  '{',
  '  "queue": "enrichment",',
  '  "leader": "worker-3",',
  '  "pollIntervalMs": 5000,',
  '  "failovers": [{ "at": "2026-09-16T08:12:04Z", "from": "worker-1", "to": "worker-3" }]',
  '}',
  FENCE,
  '',
  `${FENCE}python`,
  'import psycopg',
  '',
  'def try_lead(conn: psycopg.Connection, queue: str) -> bool:',
  '    with conn.cursor() as cur:',
  '        cur.execute("SELECT pg_try_advisory_lock(hashtext(%s))", (queue,))',
  '        return bool(cur.fetchone()[0])',
  FENCE,
  '',
  `${FENCE}diff`,
  '--- a/src/server/jobs/queue/claim.ts',
  '+++ b/src/server/jobs/queue/claim.ts',
  '@@ -12,7 +12,7 @@ export async function claim(queue: string) {',
  '-  const lock = await redis.set(`lock:${queue}`, workerId, "NX", "PX", 30_000);',
  '-  if (!lock) return null;',
  '+  const leading = await tryLead(queue);',
  '+  if (!leading) return null;',
  '   return nextJob(queue);',
  ' }',
  FENCE,
  '',
  '## Math',
  '',
  'Expected takeover time with poll interval $T$ and $n$ followers is $\\mathbb{E}[t] = \\frac{T}{n + 1}$, bounded by $T = 5\\,\\text{s}$.',
  '',
  '$$',
  'P(\\text{duplicate run}) = 1 - \\prod_{i=1}^{n} \\left(1 - p_i\\right) \\approx \\sum_{i=1}^{n} p_i',
  '$$',
  '',
  '## Diagrams',
  '',
  `${FENCE}mermaid`,
  'flowchart TD',
  '  A[Worker starts] --> B{pg_try_advisory_lock}',
  '  B -- locked --> C[Drain queue]',
  '  B -- busy --> D[Poll every 5 s]',
  '  D --> B',
  '  C --> E[Connection lost]',
  '  E --> B',
  FENCE,
  '',
  `${FENCE}mermaid`,
  'sequenceDiagram',
  '  participant W1 as Worker 1',
  '  participant PG as Postgres',
  '  participant W2 as Worker 2',
  '  W1->>PG: pg_try_advisory_lock(q)',
  '  PG-->>W1: true',
  '  W2->>PG: pg_try_advisory_lock(q)',
  '  PG-->>W2: false',
  '  Note over W1,PG: W1 disconnects',
  '  W2->>PG: pg_try_advisory_lock(q)',
  '  PG-->>W2: true',
  FENCE,
  '',
  'That is the whole change. The Redis client removal lands in the next PR.',
].join('\n');

/** Every fenced code language the document must contain (asserted by the test). */
export const FIXTURE_MARKDOWN_FENCES = ['ts', 'tsx', 'bash', 'json', 'python', 'diff', 'mermaid'] as const;
