import type { HighlightLang } from '@/lib/code-theme';

/**
 * One short, realistic snippet per bundled grammar. Used by
 * `shiki.test.ts` (Bun) and `scripts/hermes-highlight-check` (the Hermes
 * runtime the app ships) to prove every grammar compiles and colours.
 */
export const HIGHLIGHT_SAMPLES: Record<HighlightLang, string> = {
  json: '{ "name": "kortix", "version": 1, "private": true }',
  jsonc: '{\n  // comment\n  "strict": true\n}',
  yaml: 'name: kortix\non:\n  push:\n    branches: [main] # trunk',
  toml: '[package]\nname = "kortix"\nversion = "1.0.0"',
  ini: '[core]\n; leading comment\neditor = vim ; trailing comment',
  dotenv: 'API_URL="https://api.kortix.com" # prod\nDEBUG=true',
  xml: '<?xml version="1.0"?>\n<note id="1"><to>Jay</to></note>',
  diff: '--- a/app.ts\n+++ b/app.ts\n@@ -1 +1 @@\n-const a = 1;\n+const a = 2;',
  html: '<!doctype html>\n<a href="/docs" class="link">Docs</a>',
  css: '.card { color: red; padding: 4px; }',
  scss: '$gap: 4px;\n.card { &:hover { margin: $gap; } }',
  less: '@gap: 4px;\n.card { margin: @gap; }',
  javascript: 'export async function load(id) {\n  return await fetch(`/api/${id}`);\n}',
  typescript: 'export const answer: number = 42;\ninterface User { id: string }',
  jsx: 'export const App = () => <div className="app">{name}</div>;',
  tsx: 'export function App({ name }: { name: string }) {\n  return <div>{name}</div>;\n}',
  vue: '<template>\n  <p>{{ msg }}</p>\n</template>\n<script setup lang="ts">\nconst msg = "hi";\n</script>',
  svelte: '<script>\n  let count = 0;\n</script>\n<button on:click={() => count++}>{count}</button>',
  astro: '---\nconst title = "Kortix";\n---\n<h1>{title}</h1>',
  markdown: '# Title\n\nSome **bold** text and `code`.\n\n- item',
  mdx: 'import { Card } from "./card";\n\n# Hello\n\n<Card title="x" />',
  python: 'def greet(name: str) -> str:\n    return f"hello {name}"  # hi',
  ruby: 'class User\n  def initialize(name)\n    @name = name\n  end\nend',
  go: 'package main\n\nfunc main() {\n\tfmt.Println("hi")\n}',
  rust: 'fn main() {\n    let x: i32 = 5;\n    println!("{}", x);\n}',
  java: 'public class App {\n  public static void main(String[] args) {}\n}',
  kotlin: 'fun main() {\n    val name = "kortix"\n    println(name)\n}',
  swift: 'struct User {\n  let name: String\n}\nlet u = User(name: "jay")',
  c: '#include <stdio.h>\nint main(void) { return 0; }',
  cpp: '#include <vector>\nint main() { std::vector<int> v{1, 2}; return 0; }',
  csharp: 'public class App {\n  public static void Main(string[] args) { }\n}',
  php: '<?php\nfunction greet(string $name): string { return "hi $name"; }',
  sql: 'SELECT id, name FROM users WHERE id = 1 ORDER BY name;',
  lua: 'local function greet(name)\n  return "hi " .. name\nend',
  r: 'greet <- function(name) {\n  paste("hi", name)\n}',
  dart: 'void main() {\n  final name = "kortix";\n  print(name);\n}',
  elixir: 'defmodule App do\n  def greet(name), do: "hi #{name}"\nend',
  bash: '#!/usr/bin/env bash\nif [ -f "$FILE" ]; then echo "found"; fi',
  powershell: 'function Get-Name { param([string]$Name) Write-Output "hi $Name" }',
  dockerfile: 'FROM node:22-alpine\nRUN npm ci\nCMD ["node", "index.js"]',
  nginx: 'server {\n  listen 80;\n  location / { proxy_pass http://app; }\n}',
  makefile: 'build:\n\tgo build -o bin/app ./cmd/app',
  hcl: 'variable "region" {\n  default = "us-east-1"\n}',
  terraform: 'resource "aws_s3_bucket" "b" {\n  bucket = "kortix"\n}',
  graphql: 'query User($id: ID!) {\n  user(id: $id) { name }\n}',
  prisma: 'model User {\n  id   Int    @id @default(autoincrement())\n  name String\n}',
  proto: 'syntax = "proto3";\nmessage User { string name = 1; }',
  mermaid: 'graph TD\n  A[Start] --> B{Ready?}\n  B -->|yes| C[Ship]',
};
