/**
 * The audit label of every API route: one line per route.
 *
 * Key: `METHOD /template` (the router's template, exactly as `app.routes`
 * lists it), `ALL /template` for a catch-all `app.all` handler, or
 * `ENTRY name` for a request the server dispatches before the router
 * (`setInboundAuditEntrypoint` in `apps/api/src/index.ts`).
 *
 * Value: `{ action, title }`, or the key of another route this one is an
 * alias of (a deprecated path, a `/*` twin, PUT next to PATCH).
 *
 * - `action`: `domain.resource.verb`, present tense (`secret.list`,
 *   `gateway.key.revoke`). When the handler writes its own audit event for the
 *   request, use that event's action: the event then becomes the request row.
 * - `title`: what the actor did, past tense, sentence case, 2 to 7 words
 *   (`Revoked LLM gateway key`). Customers read it in the audit log.
 *
 * `apps/api/src/__tests__/unit-audit-route-labels.test.ts` fails for a route
 * without a line and for a line without a route.
 */
import type { AuditRouteLabel } from './audit-labels';

// biome-ignore format: one route per line, so a diff names exactly the route that changed
export const AUDIT_ROUTE_LABELS: Readonly<Record<string, AuditRouteLabel | string>> = {
  'GET /.well-known/oauth-authorization-server': { action: 'oauth.server_metadata.read', title: 'Viewed OAuth server metadata' },
  'GET /health': { action: 'system.health.read', title: 'Checked API health' },
  'GET /health/live': { action: 'system.health.liveness.read', title: 'Checked API liveness' },
  'GET /health/ready': { action: 'system.health.readiness.read', title: 'Checked API readiness' },
  'POST /internal/gateway/authenticate': { action: 'gateway.internal.token.authenticate', title: 'Authenticated LLM gateway token' },
  'POST /internal/gateway/authorize': { action: 'gateway.internal.request.authorize', title: 'Authorized LLM gateway request' },
  'POST /internal/gateway/billing': { action: 'gateway.internal.billing.check', title: 'Checked LLM billing eligibility' },
  'POST /internal/gateway/budget-check': { action: 'gateway.internal.budget.check', title: 'Checked LLM gateway budget' },
  'POST /internal/gateway/models': { action: 'gateway.internal.model.list', title: 'Resolved LLM gateway model catalog' },
  'POST /internal/gateway/pool-rate-limit': { action: 'gateway.internal.pool_key.cool_down', title: 'Cooled down pooled provider key' },
  'POST /internal/gateway/resolve-route': { action: 'gateway.internal.route.resolve', title: 'Resolved LLM model routing' },
  'POST /internal/gateway/resolve-upstream': { action: 'gateway.internal.upstream.resolve', title: 'Resolved LLM upstream provider' },
  'POST /internal/gateway/trace': { action: 'gateway.internal.trace.record', title: 'Recorded LLM gateway trace' },
  'POST /internal/gateway/usage': { action: 'gateway.internal.usage.record', title: 'Recorded LLM gateway usage' },
  'GET /metrics': { action: 'system.metrics.read', title: 'Viewed system metrics' },
  'GET /scim/v2/accounts/:accountId/Groups': { action: 'scim.group.list', title: 'Listed SCIM groups' },
  'POST /scim/v2/accounts/:accountId/Groups': { action: 'scim.group.create', title: 'Provisioned SCIM group' },
  'DELETE /scim/v2/accounts/:accountId/Groups/:groupId': { action: 'scim.group.delete', title: 'Deleted SCIM group' },
  'GET /scim/v2/accounts/:accountId/Groups/:groupId': { action: 'scim.group.read', title: 'Viewed SCIM group' },
  'PATCH /scim/v2/accounts/:accountId/Groups/:groupId': { action: 'scim.group.update', title: 'Updated SCIM group' },
  'PUT /scim/v2/accounts/:accountId/Groups/:groupId': 'PATCH /scim/v2/accounts/:accountId/Groups/:groupId',
  'GET /scim/v2/accounts/:accountId/ResourceTypes': { action: 'scim.resource_type.list', title: 'Listed SCIM resource types' },
  'GET /scim/v2/accounts/:accountId/ResourceTypes/:id': { action: 'scim.resource_type.read', title: 'Viewed SCIM resource type' },
  'GET /scim/v2/accounts/:accountId/Schemas': { action: 'scim.schema.list', title: 'Listed SCIM schemas' },
  'GET /scim/v2/accounts/:accountId/Schemas/:id': { action: 'scim.schema.read', title: 'Viewed SCIM schema' },
  'GET /scim/v2/accounts/:accountId/ServiceProviderConfig': { action: 'scim.service_provider_config.read', title: 'Viewed SCIM service provider config' },
  'GET /scim/v2/accounts/:accountId/Users': { action: 'scim.user.list', title: 'Listed SCIM users' },
  'POST /scim/v2/accounts/:accountId/Users': { action: 'scim.user.create', title: 'Provisioned SCIM user' },
  'DELETE /scim/v2/accounts/:accountId/Users/:userId': { action: 'scim.user.delete', title: 'Deprovisioned SCIM user' },
  'GET /scim/v2/accounts/:accountId/Users/:userId': { action: 'scim.user.read', title: 'Viewed SCIM user' },
  'PATCH /scim/v2/accounts/:accountId/Users/:userId': { action: 'scim.user.update', title: 'Updated SCIM user' },
  'PUT /scim/v2/accounts/:accountId/Users/:userId': 'PATCH /scim/v2/accounts/:accountId/Users/:userId',
  'POST /v1/access/check-email': { action: 'auth.email.check', title: 'Checked sign-in email' },
  'POST /v1/access/request-access': { action: 'auth.access_request.create', title: 'Requested early access' },
  'GET /v1/access/signup-status': { action: 'auth.signup_status.read', title: 'Viewed signup status' },
  'GET /v1/account-invites': { action: 'invite.received.list', title: 'Listed received invitations' },
  'GET /v1/account-invites/:inviteId': { action: 'invite.read', title: 'Viewed account invitation' },
  'POST /v1/account-invites/:inviteId/accept': { action: 'invite.accept', title: 'Accepted account invitation' },
  'POST /v1/account-invites/:inviteId/decline': { action: 'invite.decline', title: 'Declined account invitation' },
  'POST /v1/account/cancel-deletion': { action: 'account.deletion.cancel', title: 'Canceled account deletion' },
  'DELETE /v1/account/delete-immediately': { action: 'account.deletion.execute', title: 'Deleted account immediately' },
  'GET /v1/account/deletion-status': { action: 'account.deletion.read', title: 'Viewed account deletion status' },
  'POST /v1/account/request-deletion': { action: 'account.deletion.request', title: 'Requested account deletion' },
  'GET /v1/accounts': { action: 'account.list', title: 'Listed accounts' },
  'POST /v1/accounts': { action: 'account.create', title: 'Created account' },
  'GET /v1/accounts/:accountId': { action: 'account.read', title: 'Viewed account' },
  'PATCH /v1/accounts/:accountId': { action: 'account.update', title: 'Renamed account' },
  'GET /v1/accounts/:accountId/audit': { action: 'iam.audit.list', title: 'Viewed audit log' },
  'GET /v1/accounts/:accountId/audit/export': { action: 'iam.audit.export', title: 'Exported audit log' },
  'POST /v1/accounts/:accountId/audit/reconcile': { action: 'iam.audit.reconcile', title: 'Reconciled audit log' },
  'GET /v1/accounts/:accountId/audit/webhooks': { action: 'iam.audit.webhook.list', title: 'Listed audit webhooks' },
  'POST /v1/accounts/:accountId/audit/webhooks': { action: 'iam.audit.webhook.create', title: 'Created audit webhook' },
  'DELETE /v1/accounts/:accountId/audit/webhooks/:webhookId': { action: 'iam.audit.webhook.delete', title: 'Deleted audit webhook' },
  'PATCH /v1/accounts/:accountId/audit/webhooks/:webhookId': { action: 'iam.audit.webhook.update', title: 'Updated audit webhook' },
  'GET /v1/accounts/:accountId/audit/webhooks/:webhookId/deliveries': { action: 'iam.audit.webhook.delivery.list', title: 'Listed audit webhook deliveries' },
  'POST /v1/accounts/:accountId/audit/webhooks/:webhookId/deliveries/:deliveryId/replay': { action: 'iam.audit.webhook.delivery.replay', title: 'Replayed audit webhook delivery' },
  'DELETE /v1/accounts/:accountId/branding': { action: 'account.branding.reset', title: 'Reset branding' },
  'GET /v1/accounts/:accountId/branding': { action: 'account.branding.read', title: 'Viewed branding' },
  'PUT /v1/accounts/:accountId/branding': { action: 'account.branding.update', title: 'Updated branding' },
  'DELETE /v1/accounts/:accountId/branding/assets/:kind': { action: 'account.branding.asset.remove', title: 'Removed branding asset' },
  'POST /v1/accounts/:accountId/branding/assets/:kind': { action: 'account.branding.asset.upload', title: 'Uploaded branding asset' },
  'GET /v1/accounts/:accountId/iam/actions': { action: 'iam.action.list', title: 'Listed IAM actions' },
  'GET /v1/accounts/:accountId/iam/agent-identities': { action: 'iam.agent_identity.list', title: 'Listed agent identities' },
  'GET /v1/accounts/:accountId/iam/assignments': { action: 'iam.assignment.list', title: 'Listed role assignments' },
  'POST /v1/accounts/:accountId/iam/assignments': { action: 'iam.assignment.granted', title: 'Granted a role' },
  'DELETE /v1/accounts/:accountId/iam/assignments/:assignmentId': { action: 'iam.assignment.revoked', title: 'Revoked a role' },
  'GET /v1/accounts/:accountId/iam/enterprise-demo': { action: 'iam.enterprise_demo.read', title: 'Viewed Enterprise preview' },
  'PUT /v1/accounts/:accountId/iam/enterprise-demo': { action: 'iam.enterprise_demo.set', title: 'Updated Enterprise preview' },
  'GET /v1/accounts/:accountId/iam/groups': { action: 'iam.group.list', title: 'Listed groups' },
  'POST /v1/accounts/:accountId/iam/groups': { action: 'iam.group.create', title: 'Created group' },
  'DELETE /v1/accounts/:accountId/iam/groups/:groupId': { action: 'iam.group.delete', title: 'Deleted group' },
  'GET /v1/accounts/:accountId/iam/groups/:groupId': { action: 'iam.group.read', title: 'Viewed group' },
  'PATCH /v1/accounts/:accountId/iam/groups/:groupId': { action: 'iam.group.update', title: 'Updated group' },
  'GET /v1/accounts/:accountId/iam/groups/:groupId/members': { action: 'iam.group.members.list', title: 'Listed group members' },
  'POST /v1/accounts/:accountId/iam/groups/:groupId/members': { action: 'iam.group.members.add', title: 'Added member to group' },
  'DELETE /v1/accounts/:accountId/iam/groups/:groupId/members/:userId': { action: 'iam.group.members.remove', title: 'Removed member from group' },
  'GET /v1/accounts/:accountId/iam/groups/:groupId/project-grants': { action: 'iam.group.project_grants.list', title: 'Listed group project access' },
  'GET /v1/accounts/:accountId/iam/members/:userId/effective': { action: 'iam.member.effective_permission.check', title: 'Checked effective permission' },
  'POST /v1/accounts/:accountId/iam/members/:userId/effective:batch': { action: 'iam.member.effective_permission.batch_check', title: 'Batch-checked effective permissions' },
  'GET /v1/accounts/:accountId/iam/members/:userId/groups': { action: 'iam.member.groups.list', title: 'Listed member groups' },
  'GET /v1/accounts/:accountId/iam/members/:userId/project-access': { action: 'iam.member.project_access.list', title: 'Listed member project access' },
  'PATCH /v1/accounts/:accountId/iam/members/:userId/super-admin': { action: 'iam.member.super_admin.set', title: 'Set super-admin status' },
  'GET /v1/accounts/:accountId/iam/mfa-required': { action: 'iam.mfa_required.read', title: 'Viewed MFA requirement' },
  'PATCH /v1/accounts/:accountId/iam/mfa-required': { action: 'iam.mfa_required.set', title: 'Changed MFA requirement' },
  'GET /v1/accounts/:accountId/iam/mfa-required/preview': { action: 'iam.mfa_required.preview', title: 'Previewed MFA enforcement' },
  'GET /v1/accounts/:accountId/iam/oauth-clients': { action: 'iam.oauth_client.list', title: 'Listed OAuth apps' },
  'POST /v1/accounts/:accountId/iam/oauth-clients': { action: 'iam.oauth_client.create', title: 'Registered an OAuth app' },
  'DELETE /v1/accounts/:accountId/iam/oauth-clients/:clientId': { action: 'iam.oauth_client.delete', title: 'Deleted an OAuth app' },
  'GET /v1/accounts/:accountId/iam/oauth-clients/:clientId': { action: 'iam.oauth_client.read', title: 'Viewed an OAuth app' },
  'PATCH /v1/accounts/:accountId/iam/oauth-clients/:clientId': { action: 'iam.oauth_client.update', title: 'Updated an OAuth app' },
  'POST /v1/accounts/:accountId/iam/oauth-clients/:clientId/rotate-secret': { action: 'iam.oauth_client.rotate_secret', title: 'Rotated an OAuth app secret' },
  'GET /v1/accounts/:accountId/iam/pat-policy': { action: 'iam.pat_policy.read', title: 'Viewed PAT policy' },
  'PATCH /v1/accounts/:accountId/iam/pat-policy': { action: 'iam.pat_policy.update', title: 'Updated PAT policy' },
  'GET /v1/accounts/:accountId/iam/permissions': { action: 'iam.permission.list', title: 'Listed the permission catalog' },
  'GET /v1/accounts/:accountId/iam/policies': { action: 'iam.policy.list', title: 'Listed IAM policies' },
  'POST /v1/accounts/:accountId/iam/policies': { action: 'iam.policy.create', title: 'Created IAM policy' },
  'DELETE /v1/accounts/:accountId/iam/policies/:policyId': { action: 'iam.policy.delete', title: 'Deleted IAM policy' },
  'PATCH /v1/accounts/:accountId/iam/policies/:policyId': { action: 'iam.policy.update', title: 'Updated IAM policy' },
  'POST /v1/accounts/:accountId/iam/policies:bulk-delete': { action: 'iam.policy.bulk_delete', title: 'Bulk deleted IAM policies' },
  'POST /v1/accounts/:accountId/iam/policies:bulk-import': { action: 'iam.policy.bulk_import', title: 'Bulk imported IAM policies' },
  'GET /v1/accounts/:accountId/iam/resource-grants': { action: 'iam.resource_grant.list', title: 'Listed resource grants' },
  'GET /v1/accounts/:accountId/iam/roles': { action: 'iam.role.list', title: 'Listed IAM roles' },
  'POST /v1/accounts/:accountId/iam/roles': { action: 'iam.role.create', title: 'Created IAM role' },
  'DELETE /v1/accounts/:accountId/iam/roles/:roleId': { action: 'iam.role.delete', title: 'Deleted IAM role' },
  'PATCH /v1/accounts/:accountId/iam/roles/:roleId': { action: 'iam.role.update', title: 'Updated IAM role' },
  'GET /v1/accounts/:accountId/iam/roles/:roleId/permissions': { action: 'iam.role.permissions.read', title: 'Viewed IAM role permissions' },
  'PUT /v1/accounts/:accountId/iam/roles/:roleId/permissions': { action: 'iam.role.permissions.set', title: 'Updated IAM role permissions' },
  'GET /v1/accounts/:accountId/iam/roles/:roleId/usage': { action: 'iam.role.usage.read', title: 'Viewed IAM role usage' },
  'GET /v1/accounts/:accountId/iam/scim/tokens': { action: 'iam.scim.token.list', title: 'Listed SCIM tokens' },
  'POST /v1/accounts/:accountId/iam/scim/tokens': { action: 'iam.scim.token.create', title: 'Created SCIM token' },
  'DELETE /v1/accounts/:accountId/iam/scim/tokens/:tokenId': { action: 'iam.scim.token.revoke', title: 'Revoked SCIM token' },
  'GET /v1/accounts/:accountId/iam/service-accounts': { action: 'iam.service_account.list', title: 'Listed service accounts' },
  'POST /v1/accounts/:accountId/iam/service-accounts': { action: 'iam.service_account.create', title: 'Created service account' },
  'DELETE /v1/accounts/:accountId/iam/service-accounts/:saId': { action: 'iam.service_account.delete', title: 'Deleted service account' },
  'POST /v1/accounts/:accountId/iam/service-accounts/:saId/disable': { action: 'iam.service_account.disable', title: 'Disabled service account' },
  'GET /v1/accounts/:accountId/iam/session-oversight': { action: 'iam.session_oversight.read', title: 'Viewed admin session access' },
  'PATCH /v1/accounts/:accountId/iam/session-oversight': { action: 'iam.session_oversight.set', title: 'Changed admin session access' },
  'GET /v1/accounts/:accountId/iam/session-policy': { action: 'iam.session_policy.read', title: 'Viewed session policy' },
  'PATCH /v1/accounts/:accountId/iam/session-policy': { action: 'iam.session_policy.update', title: 'Updated session policy' },
  'GET /v1/accounts/:accountId/iam/sessions': { action: 'iam.session.list', title: 'Listed sign-in sessions' },
  'POST /v1/accounts/:accountId/iam/sessions/:sessionId/revoke': { action: 'iam.session.revoke', title: 'Revoked sign-in session' },
  'GET /v1/accounts/:accountId/iam/sso/mappings': { action: 'iam.sso.mapping.list', title: 'Listed SSO group mappings' },
  'POST /v1/accounts/:accountId/iam/sso/mappings': { action: 'iam.sso.mapping.create', title: 'Added SSO group mapping' },
  'DELETE /v1/accounts/:accountId/iam/sso/mappings/:mappingId': { action: 'iam.sso.mapping.delete', title: 'Removed SSO group mapping' },
  'DELETE /v1/accounts/:accountId/iam/sso/provider': { action: 'iam.sso.provider.delete', title: 'Removed SSO provider' },
  'GET /v1/accounts/:accountId/iam/sso/provider': { action: 'iam.sso.provider.read', title: 'Viewed SSO provider' },
  'PUT /v1/accounts/:accountId/iam/sso/provider': { action: 'iam.sso.provider.update', title: 'Updated SSO provider' },
  'POST /v1/accounts/:accountId/iam/sso/provider/from-metadata': { action: 'iam.sso.provider.create', title: 'Created SSO provider' },
  'GET /v1/accounts/:accountId/invites': { action: 'invite.list', title: 'Listed pending invitations' },
  'DELETE /v1/accounts/:accountId/invites/:inviteId': { action: 'invite.cancel', title: 'Canceled account invitation' },
  'POST /v1/accounts/:accountId/invites/:inviteId/resend': { action: 'invite.resend', title: 'Resent account invitation' },
  'POST /v1/accounts/:accountId/leave': { action: 'member.leave', title: 'Left account' },
  'GET /v1/accounts/:accountId/members': { action: 'member.list', title: 'Listed account members' },
  'POST /v1/accounts/:accountId/members': { action: 'member.invite', title: 'Invited member to account' },
  'DELETE /v1/accounts/:accountId/members/:userId': { action: 'member.remove', title: 'Removed member from account' },
  'PATCH /v1/accounts/:accountId/members/:userId': { action: 'member.role.update', title: 'Changed member role' },
  'GET /v1/accounts/:accountId/secret-resources': { action: 'secret.account_resource.list', title: 'Listed pooled provider keys' },
  'POST /v1/accounts/:accountId/secret-resources': { action: 'secret.account_resource.create', title: 'Added pooled provider key' },
  'DELETE /v1/accounts/:accountId/secret-resources/:secretId': { action: 'secret.account_resource.delete', title: 'Deleted pooled provider key' },
  'PUT /v1/accounts/:accountId/secret-resources/:secretId/access': { action: 'secret.account_resource.access.set', title: 'Set pooled provider key access' },
  'DELETE /v1/accounts/:accountId/secret-resources/:secretId/grants/:userId': { action: 'secret.account_resource.revoke', title: 'Revoked pooled provider key grant' },
  'PUT /v1/accounts/:accountId/secret-resources/:secretId/grants/:userId': { action: 'secret.account_resource.grant', title: 'Granted pooled provider key' },
  'PUT /v1/accounts/:accountId/secret-resources/:secretId/value': { action: 'secret.account_resource.rotate', title: 'Rotated pooled provider key' },
  'GET /v1/accounts/me': { action: 'auth.identity.read', title: 'Viewed own identity' },
  'GET /v1/accounts/tokens': { action: 'account.token.list', title: 'Listed personal access tokens' },
  'POST /v1/accounts/tokens': { action: 'account.token.create', title: 'Created personal access token' },
  'DELETE /v1/accounts/tokens/:tokenId': { action: 'account.token.revoke', title: 'Revoked personal access token' },
  'GET /v1/admin/analytics/activity': { action: 'admin.analytics.activity.read', title: 'Viewed platform activity analytics' },
  'GET /v1/admin/analytics/usage': { action: 'admin.analytics.usage.read', title: 'Viewed platform credit burn analytics' },
  'GET /v1/admin/api/accounts': { action: 'admin.account.list', title: 'Listed all platform accounts' },
  'POST /v1/admin/api/accounts/:id/credits': { action: 'admin.account.credit.grant', title: 'Granted account credits' },
  'POST /v1/admin/api/accounts/:id/credits/debit': { action: 'admin.account.credit.debit', title: 'Debited account credits' },
  'POST /v1/admin/api/accounts/:id/enterprise-demo': { action: 'admin.account.enterprise_demo.set', title: 'Set enterprise demo flag' },
  'POST /v1/admin/api/accounts/:id/enterprise-entitlement': { action: 'admin.account.enterprise_entitlement.set', title: 'Set enterprise entitlement flag' },
  'GET /v1/admin/api/accounts/:id/ledger': { action: 'admin.account.ledger.list', title: 'Viewed account credit ledger' },
  'POST /v1/admin/api/accounts/:id/managed-models': { action: 'admin.account.managed_models.set', title: 'Set managed-models override' },
  'POST /v1/admin/api/accounts/:id/members/:userId/role': { action: 'admin.account.member_role.set', title: 'Changed account member role' },
  'PUT /v1/admin/api/accounts/:id/overrides': { action: 'admin.account.overrides.set', title: 'Set account entitlement overrides' },
  'GET /v1/admin/api/accounts/:id/projects': { action: 'admin.account.project.list', title: 'Listed account projects as admin' },
  'POST /v1/admin/api/accounts/:id/session-limit': { action: 'admin.account.session_limit.set', title: 'Updated account session limit' },
  'GET /v1/admin/api/accounts/:id/subscription': { action: 'admin.account.subscription.read', title: 'Viewed account Stripe subscription' },
  'POST /v1/admin/api/accounts/:id/tier': { action: 'admin.account.tier.set', title: 'Updated account tier' },
  'DELETE /v1/admin/api/accounts/:id/trial': { action: 'admin.account.trial.revoke', title: 'Revoked account trial' },
  'POST /v1/admin/api/accounts/:id/trial': { action: 'admin.account.trial.grant', title: 'Granted account trial' },
  'GET /v1/admin/api/accounts/:id/users': { action: 'admin.account.member.list', title: 'Listed account members as admin' },
  'POST /v1/admin/api/impersonate': { action: 'admin.impersonate.start', title: 'Started account impersonation' },
  'DELETE /v1/admin/api/impersonate/:grantId': { action: 'admin.impersonate.stop', title: 'Stopped account impersonation' },
  'GET /v1/admin/api/impersonate/active': { action: 'admin.impersonate.list', title: 'Listed active impersonation grants' },
  'GET /v1/admin/api/projects': { action: 'admin.project.list', title: 'Listed all platform projects' },
  'GET /v1/admin/api/provider-analytics': { action: 'admin.sandbox_provider.analytics.read', title: 'Viewed sandbox provider analytics' },
  'GET /v1/admin/api/provider-distribution': { action: 'admin.sandbox_provider.distribution.read', title: 'Viewed sandbox provider distribution' },
  'PUT /v1/admin/api/provider-distribution': { action: 'admin.sandbox_provider.distribution.update', title: 'Updated sandbox provider distribution' },
  'GET /v1/admin/api/provider-fallback': { action: 'admin.sandbox_provider.fallback.read', title: 'Viewed sandbox provider fallback' },
  'PUT /v1/admin/api/provider-fallback': { action: 'admin.sandbox_provider.fallback.update', title: 'Updated sandbox provider fallback' },
  'GET /v1/admin/api/sandboxes': { action: 'admin.sandbox.list', title: 'Listed all platform sandboxes' },
  'POST /v1/admin/api/sandboxes/:sessionId/migrate': { action: 'admin.sandbox.migrate', title: 'Migrated sandbox to another provider' },
  'GET /v1/approval-links/:token': { action: 'approval.link.read', title: 'Viewed approval link' },
  'GET /v1/apps/edge/tls-check': 'GET /v1/edge/tls-check',
  'POST /v1/auth/logout': { action: 'auth.logout', title: 'Signed out' },
  'POST /v1/auth/mfa/factors': { action: 'auth.mfa.factor.create', title: 'Enrolled a second factor' },
  'DELETE /v1/auth/mfa/factors/:factorId': { action: 'auth.mfa.factor.delete', title: 'Removed a second factor' },
  'POST /v1/auth/mfa/factors/:factorId/challenge': { action: 'auth.mfa.challenge.create', title: 'Started a second-factor challenge' },
  'POST /v1/auth/mfa/factors/:factorId/verify': { action: 'auth.mfa.factor.verify', title: 'Verified a second factor' },
  'POST /v1/auth/oauth/exchange': { action: 'auth.social_sign_in.complete', title: 'Completed a social sign-in' },
  'POST /v1/auth/password/reset': { action: 'auth.password_reset.send', title: 'Requested a password reset' },
  'POST /v1/auth/password/update': { action: 'auth.password.update', title: 'Changed password' },
  'POST /v1/auth/refresh': { action: 'auth.session.refresh', title: 'Refreshed a sign-in session' },
  'POST /v1/auth/sign-in/magic-link': { action: 'auth.magic_link.send', title: 'Requested a sign-in link' },
  'POST /v1/auth/sign-in/oauth': { action: 'auth.social_sign_in.start', title: 'Started a social sign-in' },
  'POST /v1/auth/sign-in/password': { action: 'auth.password.authenticate', title: 'Signed in with a password' },
  'POST /v1/auth/sign-in/sso': { action: 'auth.sso_sign_in.start', title: 'Started an SSO sign-in' },
  'POST /v1/auth/sign-out': 'POST /v1/auth/logout',
  'POST /v1/auth/signup': { action: 'auth.user.create', title: 'Signed up' },
  'GET /v1/auth/user': { action: 'auth.user.read', title: 'Viewed signed-in user' },
  'PATCH /v1/auth/user': { action: 'auth.profile.update', title: 'Updated profile' },
  'POST /v1/auth/verify-otp': { action: 'auth.otp.verify', title: 'Verified a sign-in code' },
  'GET /v1/billing/account-state': { action: 'billing.account_state.read', title: 'Viewed billing status' },
  'GET /v1/billing/account-state/minimal': { action: 'billing.account_state.summary.read', title: 'Viewed billing summary' },
  'POST /v1/billing/account/cancel-deletion': 'POST /v1/account/cancel-deletion',
  'DELETE /v1/billing/account/delete-immediately': 'DELETE /v1/account/delete-immediately',
  'GET /v1/billing/account/deletion-status': 'GET /v1/account/deletion-status',
  'POST /v1/billing/account/request-deletion': 'POST /v1/account/request-deletion',
  'POST /v1/billing/auto-topup/configure': { action: 'billing.auto_topup.update', title: 'Configured credit auto top-up' },
  'GET /v1/billing/auto-topup/settings': { action: 'billing.auto_topup.read', title: 'Viewed auto top-up settings' },
  'GET /v1/billing/auto-topup/setup-status': { action: 'billing.auto_topup.setup_status.read', title: 'Viewed auto top-up setup status' },
  'POST /v1/billing/cancel-scheduled-change': { action: 'billing.subscription.scheduled_change.cancel', title: 'Canceled scheduled plan change' },
  'POST /v1/billing/cancel-subscription': { action: 'billing.subscription.cancel', title: 'Canceled subscription' },
  'GET /v1/billing/checkout-session/:sessionId': { action: 'billing.checkout_session.read', title: 'Viewed checkout session' },
  'POST /v1/billing/claim-per-seat': { action: 'billing.per_seat.migrate', title: 'Migrated to per-seat pricing' },
  'POST /v1/billing/confirm-checkout-session': { action: 'billing.checkout_session.confirm', title: 'Confirmed checkout session' },
  'POST /v1/billing/confirm-inline-checkout': { action: 'billing.inline_checkout.confirm', title: 'Confirmed inline checkout' },
  'POST /v1/billing/create-checkout-session': { action: 'billing.checkout_session.create', title: 'Created subscription checkout session' },
  'POST /v1/billing/create-inline-checkout': { action: 'billing.inline_checkout.create', title: 'Created inline checkout' },
  'POST /v1/billing/create-per-seat-checkout': { action: 'billing.per_seat_checkout.create', title: 'Created per-seat checkout session' },
  'POST /v1/billing/create-portal-session': { action: 'billing.portal_session.create', title: 'Created Stripe portal session' },
  'GET /v1/billing/credit-breakdown': { action: 'billing.credit_breakdown.read', title: 'Viewed credit breakdown' },
  'GET /v1/billing/credit-usage': { action: 'billing.credit_usage.list', title: 'Viewed credit usage' },
  'POST /v1/billing/cron/free-tier-rotation': { action: 'billing.cron.free_tier_credit.rotate', title: 'Ran free-tier credit rotation' },
  'POST /v1/billing/cron/trial-expiry': { action: 'billing.cron.trial.expire', title: 'Ran trial expiry sweep' },
  'POST /v1/billing/cron/yearly-rotation': { action: 'billing.cron.yearly_credit.rotate', title: 'Ran yearly credit rotation' },
  'POST /v1/billing/deduct': { action: 'billing.credit.llm_usage.deduct', title: 'Deducted credits for LLM usage' },
  'POST /v1/billing/deduct-usage': { action: 'billing.credit.agent_usage.deduct', title: 'Deducted credits for agent run' },
  'GET /v1/billing/proration-preview': { action: 'billing.proration.preview', title: 'Previewed plan change proration' },
  'POST /v1/billing/purchase-credits': { action: 'billing.credit_purchase.start', title: 'Started credit purchase checkout' },
  'POST /v1/billing/reactivate-subscription': { action: 'billing.subscription.reactivate', title: 'Reactivated subscription' },
  'POST /v1/billing/schedule-downgrade': { action: 'billing.subscription.downgrade.schedule', title: 'Scheduled plan downgrade' },
  'POST /v1/billing/sync-seat-quantity': { action: 'billing.seat_quantity.sync', title: 'Synchronized seat quantity' },
  'POST /v1/billing/sync-subscription': { action: 'billing.subscription.sync', title: 'Synchronized subscription' },
  'GET /v1/billing/tier-configurations': { action: 'billing.tier_configuration.list', title: 'Viewed tier configurations' },
  'GET /v1/billing/transactions': { action: 'billing.transaction.list', title: 'Listed credit transactions' },
  'GET /v1/billing/transactions/summary': { action: 'billing.transaction.summary.read', title: 'Viewed transaction summary' },
  'GET /v1/billing/usage-history': { action: 'billing.usage_history.read', title: 'Viewed credit usage history' },
  'POST /v1/billing/webhook/revenuecat': 'POST /v1/billing/webhooks/revenuecat',
  'POST /v1/billing/webhook/stripe': 'POST /v1/billing/webhooks/stripe',
  'POST /v1/billing/webhooks/revenuecat': { action: 'billing.webhook.revenuecat.receive', title: 'Received RevenueCat billing webhook' },
  'POST /v1/billing/webhooks/stripe': { action: 'billing.webhook.stripe.receive', title: 'Received Stripe billing webhook' },
  'POST /v1/channels/slack/identity/bind': { action: 'channel.slack.identity.connect', title: 'Linked Slack identity' },
  'GET /v1/channels/slack/identity/login/:token': { action: 'channel.slack.login_link.read', title: 'Opened Slack login link' },
  'POST /v1/channels/teams/identity/bind': { action: 'channel.teams.identity.connect', title: 'Linked Teams identity' },
  'GET /v1/channels/teams/identity/login/:token': { action: 'channel.teams.login_link.read', title: 'Opened Teams login link' },
  'POST /v1/connectors/attachments': { action: 'connector.attachment.upload', title: 'Uploaded connector attachment' },
  'POST /v1/connectors/call': { action: 'connector.action.run', title: 'Requested connector action' },
  'GET /v1/connectors/catalog': { action: 'connector.catalog.list', title: 'Viewed connector catalog' },
  'GET /v1/connectors/connect-status': { action: 'connector.easy_connect_status.read', title: 'Viewed easy-connect status' },
  'GET /v1/connectors/connectors': 'GET /v1/connectors/catalog',
  'GET /v1/connectors/oauth2/callback': { action: 'connector.oauth2.complete', title: 'Completed connector OAuth authorization' },
  'POST /v1/connectors/projects/:projectId/attachments': 'POST /v1/connectors/attachments',
  'POST /v1/connectors/projects/:projectId/call': 'POST /v1/connectors/call',
  'GET /v1/connectors/projects/:projectId/catalog': 'GET /v1/connectors/catalog',
  'GET /v1/connectors/projects/:projectId/connect/sections': { action: 'connector.easy_connect.section.list', title: 'Browsed easy-connect categories' },
  'GET /v1/connectors/projects/:projectId/connect/toolkits': { action: 'connector.easy_connect.toolkit.list', title: 'Browsed easy-connect apps' },
  'GET /v1/connectors/projects/:projectId/connectors': { action: 'connector.list', title: 'Listed connectors' },
  'POST /v1/connectors/projects/:projectId/connectors': { action: 'connector.create', title: 'Created or updated connector' },
  'DELETE /v1/connectors/projects/:projectId/connectors/:slug': { action: 'connector.delete', title: 'Deleted connector' },
  'GET /v1/connectors/projects/:projectId/connectors/:slug/accounts': { action: 'connector.account.list', title: 'Listed connector accounts' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/authorization-strategy': { action: 'connector.authorization_strategy.update', title: 'Updated connector authorization strategy' },
  'GET /v1/connectors/projects/:projectId/connectors/:slug/config': { action: 'connector.config.read', title: 'Viewed connector configuration' },
  'POST /v1/connectors/projects/:projectId/connectors/:slug/connect': { action: 'connector.easy_connect.start', title: 'Started easy-connect authorization' },
  'POST /v1/connectors/projects/:projectId/connectors/:slug/connect/finalize': { action: 'connector.easy_connect.finalize', title: 'Finished easy-connect authorization' },
  'DELETE /v1/connectors/projects/:projectId/connectors/:slug/credential': { action: 'connector.credential.delete', title: 'Removed connector credential' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/credential': { action: 'connector.credential.set', title: 'Set connector credential' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/credential-mode': { action: 'connector.credential_mode.update', title: 'Updated connector credential mode' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/name': { action: 'connector.name.update', title: 'Renamed connector' },
  'GET /v1/connectors/projects/:projectId/connectors/:slug/policies': { action: 'connector.policy.list', title: 'Listed connector policies' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/policies': { action: 'connector.policy.update', title: 'Updated connector policies' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/secret-binding': { action: 'connector.secret_binding.update', title: 'Updated connector secret binding' },
  'PUT /v1/connectors/projects/:projectId/connectors/:slug/sensitive': { action: 'connector.sensitive.set', title: 'Set connector sensitive flag' },
  'POST /v1/connectors/projects/:projectId/connectors/auth-discovery': { action: 'connector.auth.preview', title: 'Previewed connector authentication' },
  'POST /v1/connectors/projects/:projectId/connectors/sync': { action: 'connector.sync', title: 'Synchronized connectors' },
  'GET /v1/connectors/projects/:projectId/discover/connectors': { action: 'connector.discover.list', title: 'Browsed connector discovery catalog' },
  'GET /v1/connectors/projects/:projectId/discover/connectors/detail': { action: 'connector.discover.detail.read', title: 'Viewed discovery catalog connector' },
  'GET /v1/connectors/projects/:projectId/discover/sections': { action: 'connector.discover.section.list', title: 'Browsed discovery catalog categories' },
  'GET /v1/connectors/projects/:projectId/pipedream/apps': { action: 'connector.pipedream.app.list', title: 'Browsed Pipedream apps' },
  'GET /v1/connectors/projects/:projectId/pipedream/sections': { action: 'connector.pipedream.section.list', title: 'Browsed Pipedream categories' },
  'GET /v1/connectors/projects/:projectId/policies': { action: 'connector.project_policy.list', title: 'Listed project connector policies' },
  'PUT /v1/connectors/projects/:projectId/policies': { action: 'connector.project_policy.update', title: 'Updated project connector policies' },
  'GET /v1/connectors/projects/:projectId/sessions/:sessionId/connect-requests': { action: 'connector.connect_request.list', title: 'Viewed pending connector authorizations' },
  'POST /v1/connectors/webhook/pipedream': { action: 'webhook.pipedream.connection.receive', title: 'Received Pipedream connection webhook' },
  'GET /v1/docs': { action: 'system.api_docs.read', title: 'Viewed API reference docs' },
  'GET /v1/edge/tls-check': { action: 'system.edge_tls.check', title: 'Checked TLS certificate eligibility' },
  'GET /v1/generation': { action: 'gateway.generation.read', title: 'Viewed LLM generation details' },
  'GET /v1/git/:project/compiled-checkout': { action: 'git.compiled_checkout.download', title: 'Downloaded compiled project checkout' },
  'GET /v1/git/:project/compiled-pi-runtime': { action: 'git.compiled_pi_runtime.download', title: 'Downloaded compiled pi worker runtime' },
  'GET /v1/git/:project/compiled-runtime': { action: 'git.compiled_runtime.download', title: 'Downloaded compiled session runtime' },
  'GET /v1/git/:project/fast-boot-bundle': { action: 'git.fast_boot_bundle.download', title: 'Downloaded fast-boot Git bundle' },
  'POST /v1/git/:project/git-receive-pack': { action: 'git.push', title: 'Pushed to Git repository' },
  'POST /v1/git/:project/git-upload-pack': { action: 'git.clone', title: 'Cloned or fetched Git repository' },
  'GET /v1/git/:project/info/refs': { action: 'git.ref.list', title: 'Listed Git repository refs' },
  'GET /v1/git/:project/project-snapshot': { action: 'git.project_snapshot.download', title: 'Requested project snapshot download' },
  'GET /v1/health': 'GET /health',
  'GET /v1/health/live': 'GET /health/live',
  'GET /v1/health/ready': 'GET /health/ready',
  'ALL /v1/llm-gateway/*': 'ALL /v1/llm/*',
  'ALL /v1/llm/*': { action: 'gateway.request.proxy', title: 'Called LLM gateway' },
  'GET /v1/marketplace/items': { action: 'marketplace.item.list', title: 'Listed marketplace items' },
  'GET /v1/marketplace/items/:id': { action: 'marketplace.item.read', title: 'Viewed marketplace item' },
  'GET /v1/marketplace/items/:id/file': { action: 'marketplace.item.file.read', title: 'Viewed marketplace item file' },
  'GET /v1/marketplace/marketplaces': { action: 'marketplace.list', title: 'Listed marketplaces' },
  'GET /v1/marketplace/marketplaces/featured': { action: 'marketplace.featured.list', title: 'Listed featured marketplaces' },
  'GET /v1/marketplace/sources': { action: 'marketplace.source.list', title: 'Listed marketplace sources' },
  'POST /v1/marketplace/sources': { action: 'marketplace.source.create', title: 'Added marketplace source' },
  'DELETE /v1/marketplace/sources/:id': { action: 'marketplace.source.delete', title: 'Removed marketplace source' },
  'GET /v1/oauth/.well-known/oauth-authorization-server': 'GET /.well-known/oauth-authorization-server',
  'GET /v1/oauth/authorize': { action: 'oauth.authorization.start', title: 'Started OAuth authorization' },
  'POST /v1/oauth/authorize/consent': { action: 'oauth.consent.answer', title: 'Submitted OAuth consent' },
  'GET /v1/oauth/authorize/consent/:requestId': { action: 'oauth.consent_request.read', title: 'Viewed OAuth consent request' },
  'POST /v1/oauth/revoke': { action: 'oauth.token.revoke', title: 'Revoked an OAuth token' },
  'POST /v1/oauth/token': { action: 'oauth.token.create', title: 'Issued an OAuth token' },
  'GET /v1/oauth/userinfo': { action: 'oauth.userinfo.read', title: 'Viewed OAuth user information' },
  'GET /v1/openapi.json': { action: 'system.openapi_spec.read', title: 'Viewed OpenAPI specification' },
  'GET /v1/ops/overview': { action: 'admin.ops.overview.read', title: 'Viewed platform operations overview' },
  'ALL /v1/p/:sandboxId/:port': 'ALL /v1/p/:sandboxId/:port/*',
  'ALL /v1/p/:sandboxId/:port/*': { action: 'sandbox.port.proxy', title: 'Accessed sandbox port' },
  'OPTIONS /v1/p/auth': { action: 'sandbox.preview.cors.check', title: 'Checked sandbox preview CORS access' },
  'POST /v1/p/auth': { action: 'sandbox.preview.authenticate', title: 'Authenticated to sandbox previews' },
  'GET /v1/p/config': { action: 'sandbox.preview.config.read', title: 'Viewed sandbox preview URL template' },
  'GET /v1/p/public-share/:token': { action: 'sandbox.public_share.read', title: 'Viewed public share link' },
  'ALL /v1/p/public-share/:token/:port': 'ALL /v1/p/public-share/:token/:port/*',
  'ALL /v1/p/public-share/:token/:port/*': { action: 'sandbox.public_share.preview.proxy', title: 'Accessed shared sandbox preview' },
  'ALL /v1/p/public-share/:token/file': 'ALL /v1/p/public-share/:token/file/*',
  'ALL /v1/p/public-share/:token/file/*': { action: 'sandbox.public_share.file.read', title: 'Viewed shared session file' },
  'GET /v1/p/share': { action: 'sandbox.port_share.list', title: 'Listed sandbox port share links' },
  'POST /v1/p/share': { action: 'sandbox.port_share.create', title: 'Created sandbox port share link' },
  'DELETE /v1/p/share/:token': { action: 'sandbox.port_share.revoke', title: 'Revoked sandbox port share link' },
  'GET /v1/platform': { action: 'platform.info.read', title: 'Viewed platform service info' },
  'POST /v1/platform/boot-timeline': { action: 'sandbox.boot_timeline.create', title: 'Recorded sandbox boot timeline' },
  'DELETE /v1/platform/github-app': { action: 'platform.github_app.disconnect', title: 'Disconnected instance GitHub integration' },
  'POST /v1/platform/github-app/app': { action: 'platform.github_app.connect', title: 'Connected existing GitHub App' },
  'GET /v1/platform/github-app/install-callback': { action: 'platform.github_app.installation.complete', title: 'Completed GitHub App installation' },
  'GET /v1/platform/github-app/manifest-callback': { action: 'platform.github_app.create', title: 'Created GitHub App from manifest' },
  'POST /v1/platform/github-app/manifest-start': { action: 'platform.github_app.manifest.start', title: 'Started GitHub App setup' },
  'GET /v1/platform/github-app/oauth/authorize': { action: 'platform.github_app.oauth.authorize', title: 'Started GitHub identity verification' },
  'GET /v1/platform/github-app/oauth/callback': { action: 'platform.github_app.oauth.complete', title: 'Completed GitHub identity verification' },
  'POST /v1/platform/github-app/pat': { action: 'platform.github_pat.connect', title: 'Connected managed git via GitHub PAT' },
  'GET /v1/platform/github-app/status': { action: 'platform.github_app.status.read', title: 'Viewed instance GitHub status' },
  'POST /v1/platform/runtime-projection': { action: 'runtime.projection.sync', title: 'Synced session runtime projection' },
  'GET /v1/platform/sandbox/version': { action: 'platform.sandbox_version.read', title: 'Viewed running sandbox version' },
  'GET /v1/platform/sandbox/version/all': { action: 'platform.sandbox_version.list', title: 'Listed sandbox versions' },
  'GET /v1/platform/sandbox/version/changelog': { action: 'platform.sandbox_version.changelog.read', title: 'Viewed sandbox changelog' },
  'GET /v1/platform/sandbox/version/latest': { action: 'platform.sandbox_version.latest.read', title: 'Viewed latest sandbox version' },
  'POST /v1/prewarm': { action: 'system.prewarm.request', title: 'Requested API prewarm' },
  'GET /v1/projects': { action: 'project.list', title: 'Listed projects' },
  'POST /v1/projects': { action: 'project.create', title: 'Created project' },
  'DELETE /v1/projects/:projectId': { action: 'project.delete', title: 'Deleted project' },
  'GET /v1/projects/:projectId': { action: 'project.read', title: 'Viewed project' },
  'PATCH /v1/projects/:projectId': { action: 'project.update', title: 'Updated project' },
  'GET /v1/projects/:projectId/access': { action: 'project.member.list', title: 'Viewed project member access' },
  'GET /v1/projects/:projectId/access-requests': { action: 'project.access_request.list', title: 'Listed project access requests' },
  'POST /v1/projects/:projectId/access-requests': { action: 'project.access_request.create', title: 'Requested project access' },
  'POST /v1/projects/:projectId/access-requests/:requestId/approve': { action: 'project.access_request.approve', title: 'Approved project access request' },
  'POST /v1/projects/:projectId/access-requests/:requestId/reject': { action: 'project.access_request.reject', title: 'Rejected project access request' },
  'DELETE /v1/projects/:projectId/access/:userId': { action: 'project.member.delete', title: 'Removed project member' },
  'PUT /v1/projects/:projectId/access/:userId': { action: 'project.member.update', title: 'Changed project member role' },
  'POST /v1/projects/:projectId/access/invite': { action: 'project.member.invite', title: 'Invited project member' },
  'GET /v1/projects/:projectId/access/pending-invites': { action: 'project.invite.list', title: 'Listed pending project invites' },
  'DELETE /v1/projects/:projectId/access/pending-invites/:inviteId': { action: 'project.invite.revoke', title: 'Revoked pending project invitation' },
  'POST /v1/projects/:projectId/access/pending-invites/:inviteId/resend': { action: 'project.invite.resend', title: 'Resent pending project invitation' },
  'GET /v1/projects/:projectId/agents/:agentName/config': { action: 'agent.config.read', title: 'Viewed agent configuration' },
  'PUT /v1/projects/:projectId/agents/:agentName/config': { action: 'agent.config.update', title: 'Updated agent configuration' },
  'PUT /v1/projects/:projectId/agents/:agentName/scope': { action: 'agent.scope.update', title: 'Updated agent access scope' },
  'GET /v1/projects/:projectId/approvals': { action: 'connector.approval.list', title: 'Listed pending connector approvals' },
  'POST /v1/projects/:projectId/approvals/:executionId': { action: 'connector.approval.resolve', title: 'Resolved connector approval' },
  'GET /v1/projects/:projectId/approvals/needs-input': { action: 'connector.approval.needs_input.list', title: 'Listed approvals needing input' },
  'GET /v1/projects/:projectId/apps': { action: 'app.list', title: 'Listed Kortix Apps' },
  'POST /v1/projects/:projectId/apps': { action: 'app.create', title: 'Created Kortix App' },
  'DELETE /v1/projects/:projectId/apps/:appId': { action: 'app.delete', title: 'Deleted Kortix App' },
  'GET /v1/projects/:projectId/apps/:appId': { action: 'app.read', title: 'Viewed Kortix App' },
  'PATCH /v1/projects/:projectId/apps/:appId': { action: 'app.update', title: 'Updated Kortix App' },
  'GET /v1/projects/:projectId/apps/:appId/access': { action: 'app.access.read', title: 'Viewed Kortix App access policy' },
  'PATCH /v1/projects/:projectId/apps/:appId/access': { action: 'app.access.update', title: 'Updated Kortix App access policy' },
  'POST /v1/projects/:projectId/apps/:appId/access-session': { action: 'app.access_session.create', title: 'Created Kortix App access session' },
  'GET /v1/projects/:projectId/apps/:appId/agents': { action: 'app.agent.list', title: 'Listed Kortix App agent grants' },
  'GET /v1/projects/:projectId/apps/:appId/deployments': { action: 'app.deployment.list', title: 'Listed Kortix App deployments' },
  'POST /v1/projects/:projectId/apps/:appId/deployments': { action: 'app.deployment.create', title: 'Deployed Kortix App' },
  'GET /v1/projects/:projectId/apps/:appId/deployments/:deploymentId': { action: 'app.deployment.read', title: 'Viewed Kortix App deployment' },
  'GET /v1/projects/:projectId/apps/:appId/deployments/:deploymentId/logs': { action: 'app.deployment.log.list', title: 'Viewed Kortix App deployment logs' },
  'POST /v1/projects/:projectId/apps/:appId/rollback': { action: 'app.rollback', title: 'Rolled back Kortix App' },
  'POST /v1/projects/:projectId/apps/:appId/start': { action: 'app.start', title: 'Started Kortix App' },
  'POST /v1/projects/:projectId/apps/:appId/stop': { action: 'app.stop', title: 'Stopped Kortix App' },
  'POST /v1/projects/:projectId/apps/artifacts': { action: 'app.artifact.create', title: 'Registered Kortix App artifact' },
  'POST /v1/projects/:projectId/apps/artifacts/:artifactId/finalize': { action: 'app.artifact.finalize', title: 'Finalized Kortix App artifact upload' },
  'POST /v1/projects/:projectId/attachments': { action: 'session.prompt_attachment.create', title: 'Started attachment upload' },
  'DELETE /v1/projects/:projectId/attachments/:attachmentId': { action: 'session.prompt_attachment.delete', title: 'Removed attachment upload' },
  'PUT /v1/projects/:projectId/attachments/:attachmentId/chunks/:index': { action: 'session.prompt_attachment.chunk.upload', title: 'Uploaded attachment chunk' },
  'POST /v1/projects/:projectId/attachments/:attachmentId/complete': { action: 'session.prompt_attachment.complete', title: 'Completed attachment upload' },
  'GET /v1/projects/:projectId/audit': { action: 'audit.project.list', title: 'Viewed project audit log' },
  'GET /v1/projects/:projectId/branches': { action: 'git.branch.list', title: 'Listed Git branches' },
  'GET /v1/projects/:projectId/change-requests': { action: 'change_request.list', title: 'Listed change requests' },
  'POST /v1/projects/:projectId/change-requests': { action: 'change_request.create', title: 'Created change request' },
  'GET /v1/projects/:projectId/change-requests/:crId': { action: 'change_request.read', title: 'Viewed change request' },
  'PATCH /v1/projects/:projectId/change-requests/:crId': { action: 'change_request.update', title: 'Updated change request' },
  'POST /v1/projects/:projectId/change-requests/:crId/close': { action: 'change_request.close', title: 'Closed change request' },
  'GET /v1/projects/:projectId/change-requests/:crId/diff': { action: 'change_request.diff.read', title: 'Viewed change request diff' },
  'POST /v1/projects/:projectId/change-requests/:crId/merge': { action: 'change_request.merge', title: 'Merged change request' },
  'GET /v1/projects/:projectId/change-requests/:crId/merge-preview': { action: 'change_request.merge.preview', title: 'Previewed change request merge' },
  'POST /v1/projects/:projectId/change-requests/:crId/reopen': { action: 'change_request.reopen', title: 'Reopened change request' },
  'POST /v1/projects/:projectId/change-requests/:crId/request-changes': { action: 'change_request.request_changes', title: 'Requested changes on change request' },
  'GET /v1/projects/:projectId/channels/bindings': { action: 'channel.binding.list', title: 'Listed channel bindings' },
  'PATCH /v1/projects/:projectId/channels/bindings/:bindingId': { action: 'channel.binding.update', title: 'Updated channel binding' },
  'POST /v1/projects/:projectId/channels/email/connect': { action: 'channel.email.connect', title: 'Connected email inbox' },
  'DELETE /v1/projects/:projectId/channels/email/installation': { action: 'channel.email.disconnect', title: 'Disconnected email inbox' },
  'GET /v1/projects/:projectId/channels/email/installation': { action: 'channel.email.installation.read', title: 'Viewed email installation' },
  'PATCH /v1/projects/:projectId/channels/email/installation': { action: 'channel.email.sender_policy.update', title: 'Updated email sender policy' },
  'GET /v1/projects/:projectId/channels/email/mode': { action: 'channel.email.mode.read', title: 'Viewed email setup options' },
  'POST /v1/projects/:projectId/channels/slack/bind-thread': { action: 'channel.slack.thread.bind', title: 'Bound session to Slack thread' },
  'POST /v1/projects/:projectId/channels/slack/connect': { action: 'channel.slack.connect', title: 'Connected Slack workspace' },
  'GET /v1/projects/:projectId/channels/slack/file': { action: 'channel.slack.file.download', title: 'Downloaded Slack file' },
  'POST /v1/projects/:projectId/channels/slack/file/upload': { action: 'channel.slack.file.upload', title: 'Uploaded file to Slack' },
  'DELETE /v1/projects/:projectId/channels/slack/installation': { action: 'channel.slack.disconnect', title: 'Disconnected Slack workspace' },
  'GET /v1/projects/:projectId/channels/slack/installation': { action: 'channel.slack.installation.read', title: 'Viewed Slack installation' },
  'GET /v1/projects/:projectId/channels/slack/mode': { action: 'channel.slack.mode.read', title: 'Viewed Slack setup options' },
  'POST /v1/projects/:projectId/channels/teams/connect': { action: 'channel.teams.connect', title: 'Connected Microsoft Teams tenant' },
  'GET /v1/projects/:projectId/channels/teams/conversations': { action: 'channel.teams.conversation.list', title: 'Listed Microsoft Teams conversations' },
  'GET /v1/projects/:projectId/channels/teams/file': { action: 'channel.teams.file.download', title: 'Downloaded Microsoft Teams file' },
  'POST /v1/projects/:projectId/channels/teams/file/upload': { action: 'channel.teams.file.upload', title: 'Uploaded file to Microsoft Teams' },
  'DELETE /v1/projects/:projectId/channels/teams/installation': { action: 'channel.teams.disconnect', title: 'Disconnected Microsoft Teams tenant' },
  'GET /v1/projects/:projectId/channels/teams/installation': { action: 'channel.teams.installation.read', title: 'Viewed Microsoft Teams installation' },
  'GET /v1/projects/:projectId/channels/teams/manifest': { action: 'channel.teams.manifest.read', title: 'Viewed Microsoft Teams app manifest' },
  'POST /v1/projects/:projectId/channels/teams/message': { action: 'channel.teams.message.send', title: 'Sent Microsoft Teams message' },
  'GET /v1/projects/:projectId/channels/teams/mode': { action: 'channel.teams.mode.read', title: 'Viewed Microsoft Teams setup options' },
  'GET /v1/projects/:projectId/cli-token': { action: 'project.cli_token.list', title: 'Listed project CLI tokens' },
  'POST /v1/projects/:projectId/cli-token': { action: 'project.cli_token.create', title: 'Created project CLI token' },
  'DELETE /v1/projects/:projectId/cli-token/:tokenId': { action: 'project.cli_token.revoke', title: 'Revoked project CLI token' },
  'GET /v1/projects/:projectId/commits': { action: 'git.commit.list', title: 'Listed Git commits' },
  'GET /v1/projects/:projectId/commits/:sha': { action: 'git.commit.read', title: 'Viewed Git commit' },
  'GET /v1/projects/:projectId/commits/:sha/diff': { action: 'git.commit.diff.read', title: 'Viewed Git commit diff' },
  'POST /v1/projects/:projectId/connect-requests': { action: 'connector.setup_link.create', title: 'Created connector setup link' },
  'GET /v1/projects/:projectId/connections': { action: 'connector.connection.list', title: 'Listed project connector accounts' },
  'POST /v1/projects/:projectId/connections': { action: 'connector.connection.create', title: 'Created connector account' },
  'PUT /v1/projects/:projectId/connections/:connectionId/activate': { action: 'connector.connection.activate', title: 'Activated connector account' },
  'POST /v1/projects/:projectId/connections/:connectionId/connect': { action: 'connector.connection.connect.start', title: 'Started connector account connection' },
  'POST /v1/projects/:projectId/connections/:connectionId/connect/finalize': { action: 'connector.connection.connect.finalize', title: 'Finalized connector account connection' },
  'PUT /v1/projects/:projectId/connections/:connectionId/credential': { action: 'connector.connection.credential.update', title: 'Updated connector account credential' },
  'PUT /v1/projects/:projectId/connections/:connectionId/default': { action: 'connector.connection.default.set', title: 'Set default connector account' },
  'PUT /v1/projects/:projectId/connections/:connectionId/label': { action: 'connector.connection.rename', title: 'Renamed connector account' },
  'GET /v1/projects/:projectId/connections/:connectionId/oauth2/application': { action: 'connector.connection.oauth.application.read', title: 'Viewed connector OAuth application' },
  'PUT /v1/projects/:projectId/connections/:connectionId/oauth2/application': { action: 'connector.connection.oauth.application.update', title: 'Updated connector OAuth application' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/authorize': { action: 'connector.connection.oauth.authorize', title: 'Started connector OAuth authorization' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/device': { action: 'connector.connection.oauth.device.start', title: 'Started connector device authorization' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/device/:sessionId': { action: 'connector.connection.oauth.device.check', title: 'Checked connector device authorization' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/discover': { action: 'connector.connection.oauth.discover', title: 'Discovered connector OAuth metadata' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/discover-resource': { action: 'connector.connection.oauth.resource.discover', title: 'Discovered MCP authorization server' },
  'POST /v1/projects/:projectId/connections/:connectionId/oauth2/register': { action: 'connector.connection.oauth.client.register', title: 'Registered connector OAuth client' },
  'GET /v1/projects/:projectId/connections/:connectionId/oauth2/status': { action: 'connector.connection.oauth.status.read', title: 'Viewed connector OAuth status' },
  'PUT /v1/projects/:projectId/connections/:connectionId/revoke': { action: 'connector.connection.revoke', title: 'Revoked connector account' },
  'GET /v1/projects/:projectId/connections/all': { action: 'connector.connection.roster.list', title: 'Listed all connector accounts' },
  'POST /v1/projects/:projectId/connections/me': { action: 'connector.connection.personal.create', title: 'Created personal connector account' },
  'POST /v1/projects/:projectId/connectors/:slug/oauth2/connection': { action: 'connector.connection.shared.create', title: 'Created shared connector account' },
  'PUT /v1/projects/:projectId/default-agent': { action: 'project.default_agent.update', title: 'Updated default agent' },
  'GET /v1/projects/:projectId/detail': { action: 'project.detail.read', title: 'Viewed project details' },
  'PATCH /v1/projects/:projectId/experimental': 'PATCH /v1/projects/:projectId/features',
  'PATCH /v1/projects/:projectId/features': { action: 'project.feature_flag.update', title: 'Updated project feature flag' },
  'GET /v1/projects/:projectId/files': { action: 'file.list', title: 'Listed project files' },
  'GET /v1/projects/:projectId/files/archive': { action: 'file.archive.download', title: 'Downloaded project files' },
  'GET /v1/projects/:projectId/files/content': { action: 'file.content.read', title: 'Viewed file content' },
  'GET /v1/projects/:projectId/files/history': { action: 'file.history.list', title: 'Viewed file history' },
  'GET /v1/projects/:projectId/files/search': { action: 'file.search', title: 'Searched project files' },
  'GET /v1/projects/:projectId/gateway/breakdown': { action: 'gateway.breakdown.read', title: 'Viewed LLM gateway usage by model' },
  'GET /v1/projects/:projectId/gateway/budgets': { action: 'gateway.budget.list', title: 'Listed LLM gateway budgets' },
  'PUT /v1/projects/:projectId/gateway/budgets': { action: 'gateway.budget.set', title: 'Set LLM gateway budget' },
  'DELETE /v1/projects/:projectId/gateway/budgets/:budgetId': { action: 'gateway.budget.delete', title: 'Deleted LLM gateway budget' },
  'GET /v1/projects/:projectId/gateway/errors': { action: 'gateway.error.list', title: 'Listed LLM gateway errors' },
  'GET /v1/projects/:projectId/gateway/keys': { action: 'gateway.key.list', title: 'Listed LLM gateway keys' },
  'POST /v1/projects/:projectId/gateway/keys': { action: 'gateway.key.create', title: 'Created LLM gateway key' },
  'DELETE /v1/projects/:projectId/gateway/keys/:keyId': { action: 'gateway.key.revoke', title: 'Revoked LLM gateway key' },
  'GET /v1/projects/:projectId/gateway/logs': { action: 'gateway.log.list', title: 'Listed LLM gateway request logs' },
  'GET /v1/projects/:projectId/gateway/logs/:logId': { action: 'gateway.log.read', title: 'Viewed LLM gateway request log' },
  'GET /v1/projects/:projectId/gateway/overview': { action: 'gateway.overview.read', title: 'Viewed LLM gateway usage overview' },
  'POST /v1/projects/:projectId/gateway/playground': { action: 'gateway.playground.send', title: 'Ran LLM gateway playground request' },
  'POST /v1/projects/:projectId/gateway/providers/:providerId/verify': { action: 'gateway.provider.verify', title: 'Verified LLM provider key' },
  'DELETE /v1/projects/:projectId/gateway/routing-policy': { action: 'gateway.routing_policy.delete', title: 'Deleted LLM gateway routing policy' },
  'GET /v1/projects/:projectId/gateway/routing-policy': { action: 'gateway.routing_policy.read', title: 'Viewed LLM gateway routing policy' },
  'PUT /v1/projects/:projectId/gateway/routing-policy': { action: 'gateway.routing_policy.update', title: 'Updated LLM gateway routing policy' },
  'POST /v1/projects/:projectId/gateway/routing-policy/preview': { action: 'gateway.routing_policy.preview', title: 'Previewed LLM gateway routing policy' },
  'GET /v1/projects/:projectId/gateway/series': { action: 'gateway.series.read', title: 'Viewed LLM gateway daily usage' },
  'GET /v1/projects/:projectId/gateway/sessions': { action: 'gateway.session_spend.list', title: 'Listed LLM gateway spend by session' },
  'PUT /v1/projects/:projectId/git-credential': { action: 'git.credential.set', title: 'Set project Git credential' },
  'POST /v1/projects/:projectId/git-token': { action: 'git.push_token.create', title: 'Created Git push token' },
  'POST /v1/projects/:projectId/git/collaborators': { action: 'git.collaborator.invite', title: 'Added Git collaborator' },
  'GET /v1/projects/:projectId/git/connection': { action: 'git.connection.read', title: 'Viewed Git connection status' },
  'PUT /v1/projects/:projectId/git/repository': { action: 'git.repository.replace', title: 'Replaced project Git repository' },
  'GET /v1/projects/:projectId/group-grants': { action: 'project.group_grant.list', title: 'Viewed project group grants' },
  'POST /v1/projects/:projectId/group-grants': { action: 'project.group_grant.create', title: 'Attached group to project' },
  'DELETE /v1/projects/:projectId/group-grants/:groupId': { action: 'project.group_grant.delete', title: 'Detached group from project' },
  'PATCH /v1/projects/:projectId/group-grants/:groupId': { action: 'project.group_grant.update', title: 'Changed group role on project' },
  'GET /v1/projects/:projectId/llm-catalog': { action: 'model.catalog.read', title: 'Viewed LLM catalog' },
  'GET /v1/projects/:projectId/llm-catalog/providers': { action: 'model.catalog.provider.list', title: 'Listed LLM catalog providers' },
  'POST /v1/projects/:projectId/manifest/validate': { action: 'project.manifest.validate', title: 'Validated project manifest' },
  'POST /v1/projects/:projectId/marketplace/install-session': { action: 'marketplace.install.start', title: 'Started marketplace install' },
  'GET /v1/projects/:projectId/model-access': { action: 'model.access.read', title: 'Viewed model access' },
  'PUT /v1/projects/:projectId/model-access': { action: 'model.access.update', title: 'Updated model access' },
  'DELETE /v1/projects/:projectId/model-defaults': { action: 'model.default.delete', title: 'Deleted model defaults' },
  'GET /v1/projects/:projectId/model-defaults': { action: 'model.default.read', title: 'Viewed model defaults' },
  'PUT /v1/projects/:projectId/model-defaults': { action: 'model.default.update', title: 'Updated model defaults' },
  'PUT /v1/projects/:projectId/model-enablement': { action: 'model.enablement.update', title: 'Updated model picker visibility' },
  'GET /v1/projects/:projectId/model-picker': { action: 'model.picker.read', title: 'Viewed model picker' },
  'POST /v1/projects/:projectId/monitors/ingest': { action: 'project.monitor.event.ingest', title: 'Ingested monitor events' },
  'GET /v1/projects/:projectId/oauth': { action: 'secret.oauth.list', title: 'Listed model provider OAuth logins' },
  'DELETE /v1/projects/:projectId/oauth/:provider': { action: 'secret.oauth.disconnected', title: 'Disconnected model provider OAuth login' },
  'POST /v1/projects/:projectId/oauth/:provider/poll': { action: 'secret.oauth.check', title: 'Checked model provider OAuth login' },
  'POST /v1/projects/:projectId/oauth/:provider/start': { action: 'secret.oauth.start', title: 'Started model provider OAuth login' },
  'PATCH /v1/projects/:projectId/onboarding': { action: 'project.onboarding.update', title: 'Updated project onboarding' },
  'GET /v1/projects/:projectId/resource-grants': { action: 'project.resource_grant.list', title: 'Viewed resource access grants' },
  'POST /v1/projects/:projectId/resource-grants': { action: 'project.resource_grant.create', title: 'Granted resource access' },
  'DELETE /v1/projects/:projectId/resource-grants/:grantId': { action: 'project.resource_grant.revoke', title: 'Revoked resource access' },
  'POST /v1/projects/:projectId/review/bulk': { action: 'review.item.bulk_resolve', title: 'Resolved review items in bulk' },
  'GET /v1/projects/:projectId/review/items': { action: 'review.item.list', title: 'Listed review items' },
  'POST /v1/projects/:projectId/review/items': { action: 'review.item.create', title: 'Submitted review item' },
  'GET /v1/projects/:projectId/review/items/:reviewItemId': { action: 'review.item.read', title: 'Viewed review item' },
  'POST /v1/projects/:projectId/review/items/:reviewItemId/act': { action: 'review.item.resolve', title: 'Resolved review item' },
  'GET /v1/projects/:projectId/runtime/prompt-attachments/:attachmentId': { action: 'runtime.prompt_attachment.read', title: 'Resolved runtime attachment descriptor' },
  'GET /v1/projects/:projectId/sandbox-health': { action: 'sandbox.health.read', title: 'Viewed sandbox health' },
  'PATCH /v1/projects/:projectId/sandbox-provider': { action: 'project.sandbox_provider.update', title: 'Updated sandbox provider' },
  'GET /v1/projects/:projectId/sandbox-provider/transition': { action: 'project.sandbox_provider.transition.read', title: 'Viewed sandbox provider transition' },
  'GET /v1/projects/:projectId/sandbox-templates': { action: 'sandbox.template.list', title: 'Listed sandbox templates' },
  'POST /v1/projects/:projectId/sandbox-templates': { action: 'sandbox.template.create', title: 'Created sandbox template' },
  'DELETE /v1/projects/:projectId/sandbox-templates/:templateId': { action: 'sandbox.template.delete', title: 'Deleted sandbox template' },
  'PATCH /v1/projects/:projectId/sandbox-templates/:templateId': { action: 'sandbox.template.update', title: 'Updated sandbox template' },
  'POST /v1/projects/:projectId/sandbox-templates/:templateId/build': { action: 'sandbox.template.build', title: 'Started sandbox template build' },
  'GET /v1/projects/:projectId/sandboxes': 'GET /v1/projects/:projectId/sandbox-templates',
  'POST /v1/projects/:projectId/secret-requests': { action: 'secret.request.create', title: 'Created secret request' },
  'GET /v1/projects/:projectId/secrets': { action: 'secret.list', title: 'Listed project secrets' },
  'POST /v1/projects/:projectId/secrets': { action: 'secret.set', title: 'Set project secret' },
  'POST /v1/projects/:projectId/secrets/:identifier/broker': { action: 'secret.broker.proxy', title: 'Sent request via secret broker' },
  'POST /v1/projects/:projectId/secrets/:identifier/grant': { action: 'secret.agent.grant', title: 'Granted secret to an agent' },
  'POST /v1/projects/:projectId/secrets/:identifier/relay': { action: 'secret.relay.stream', title: 'Streamed request via secret relay' },
  'PUT /v1/projects/:projectId/secrets/:identifier/strategy': { action: 'secret.strategy.changed', title: 'Updated secret delivery strategy' },
  'DELETE /v1/projects/:projectId/secrets/:name': { action: 'secret.deleted', title: 'Removed shared secret' },
  'DELETE /v1/projects/:projectId/secrets/:name/personal': { action: 'secret.personal.delete', title: 'Removed personal secret' },
  'PUT /v1/projects/:projectId/secrets/:name/personal': { action: 'secret.personal.set', title: 'Set personal secret' },
  'POST /v1/projects/:projectId/secrets/sync': { action: 'secret.sync', title: 'Synced secrets to active sandboxes' },
  'GET /v1/projects/:projectId/sessions': { action: 'session.list', title: 'Listed project sessions' },
  'POST /v1/projects/:projectId/sessions': { action: 'session.create', title: 'Created session' },
  'DELETE /v1/projects/:projectId/sessions/:sessionId': { action: 'session.delete', title: 'Deleted session' },
  'GET /v1/projects/:projectId/sessions/:sessionId': { action: 'session.read', title: 'Viewed session' },
  'PATCH /v1/projects/:projectId/sessions/:sessionId': { action: 'session.update', title: 'Updated session' },
  'POST /v1/projects/:projectId/sessions/:sessionId/attachments': { action: 'session.attachment.upload', title: 'Uploaded session attachment' },
  'GET /v1/projects/:projectId/sessions/:sessionId/attachments/:attachmentId': { action: 'session.attachment.download', title: 'Downloaded session attachment' },
  'GET /v1/projects/:projectId/sessions/:sessionId/audit': { action: 'audit.session.list', title: 'Viewed session audit log' },
  'POST /v1/projects/:projectId/sessions/:sessionId/audit/events': { action: 'audit.session.ingest', title: 'Ingested session audit events' },
  'POST /v1/projects/:projectId/sessions/:sessionId/commit-push': { action: 'session.git.push', title: 'Committed and pushed session changes' },
  'GET /v1/projects/:projectId/sessions/:sessionId/config': { action: 'session.agent_config.check', title: 'Checked session agent config freshness' },
  'GET /v1/projects/:projectId/sessions/:sessionId/environment': { action: 'session.environment.read', title: 'Viewed session environment' },
  'POST /v1/projects/:projectId/sessions/:sessionId/environment/ensure': { action: 'session.environment.start', title: 'Started session environment' },
  'POST /v1/projects/:projectId/sessions/:sessionId/environment/stop': { action: 'session.environment.stop', title: 'Stopped session environment' },
  'GET /v1/projects/:projectId/sessions/:sessionId/events': { action: 'session.event.stream', title: 'Streamed session events' },
  'PUT /v1/projects/:projectId/sessions/:sessionId/model': { action: 'session.model.update', title: 'Changed session model' },
  'GET /v1/projects/:projectId/sessions/:sessionId/open-bundle': 'GET /v1/projects/:projectId/sessions/:sessionId/snapshot',
  'GET /v1/projects/:projectId/sessions/:sessionId/previews': { action: 'session.preview.list', title: 'Listed session preview candidates' },
  'GET /v1/projects/:projectId/sessions/:sessionId/prompts': { action: 'session.prompt.list', title: 'Viewed queued session prompts' },
  'POST /v1/projects/:projectId/sessions/:sessionId/prompts': { action: 'session.prompt.send', title: 'Queued a session prompt' },
  'DELETE /v1/projects/:projectId/sessions/:sessionId/prompts/:promptId': { action: 'session.prompt.delete', title: 'Removed a queued session prompt' },
  'POST /v1/projects/:projectId/sessions/:sessionId/prompts/:promptId/retry': { action: 'session.prompt.retry', title: 'Retried a queued session prompt' },
  'POST /v1/projects/:projectId/sessions/:sessionId/prompts/hold': { action: 'session.prompt.hold.set', title: 'Set session prompt queue hold' },
  'GET /v1/projects/:projectId/sessions/:sessionId/provider-secret-pools': { action: 'session.provider_secret_pool.list', title: 'Listed session provider secret pools' },
  'GET /v1/projects/:projectId/sessions/:sessionId/provider-secret-pools/:providerId': { action: 'session.provider_secret_pool.read', title: 'Viewed session provider secret pool' },
  'PUT /v1/projects/:projectId/sessions/:sessionId/provider-secret-pools/:providerId': { action: 'session.provider_secret_pool.update', title: 'Updated session provider secret pool' },
  'GET /v1/projects/:projectId/sessions/:sessionId/public-shares': { action: 'session.public_share.list', title: 'Listed public share links' },
  'POST /v1/projects/:projectId/sessions/:sessionId/public-shares': { action: 'session.public_share.create', title: 'Created public share link' },
  'DELETE /v1/projects/:projectId/sessions/:sessionId/public-shares/:shareId': { action: 'session.public_share.revoke', title: 'Revoked public share link' },
  'GET /v1/projects/:projectId/sessions/:sessionId/question': { action: 'session.question.read', title: 'Viewed open session question' },
  'POST /v1/projects/:projectId/sessions/:sessionId/question': { action: 'session.question.answer', title: 'Answered session question' },
  'POST /v1/projects/:projectId/sessions/:sessionId/reload': { action: 'session.agent_config.reload', title: 'Reloaded session agent config' },
  'POST /v1/projects/:projectId/sessions/:sessionId/reload-stream': 'POST /v1/projects/:projectId/sessions/:sessionId/reload',
  'POST /v1/projects/:projectId/sessions/:sessionId/restart': { action: 'session.restart', title: 'Restarted session' },
  'GET /v1/projects/:projectId/sessions/:sessionId/scope': { action: 'session.scope.read', title: 'Viewed session scope' },
  'PUT /v1/projects/:projectId/sessions/:sessionId/scope': { action: 'session.scope.update', title: 'Updated session scope' },
  'PUT /v1/projects/:projectId/sessions/:sessionId/sharing': { action: 'session.sharing.update', title: 'Updated session sharing' },
  'GET /v1/projects/:projectId/sessions/:sessionId/snapshot': { action: 'session.snapshot.read', title: 'Opened session' },
  'POST /v1/projects/:projectId/sessions/:sessionId/start': { action: 'session.start', title: 'Started session' },
  'POST /v1/projects/:projectId/sessions/:sessionId/stop': { action: 'session.stop', title: 'Stopped session' },
  'GET /v1/projects/:projectId/sessions/:sessionId/transcript': { action: 'session.transcript.read', title: 'Viewed session transcript' },
  'GET /v1/projects/:projectId/sessions/:sessionId/turn': { action: 'session.turn.read', title: 'Viewed session turn state' },
  'POST /v1/projects/:projectId/sessions/warm': { action: 'session.warm.create', title: 'Warmed session sandbox' },
  'POST /v1/projects/:projectId/sessions/warm/claim': { action: 'session.warm.claim', title: 'Claimed warm session sandbox' },
  'GET /v1/projects/:projectId/snapshots': { action: 'snapshot.list', title: 'Listed sandbox snapshots' },
  'POST /v1/projects/:projectId/snapshots/fix-with-agent': { action: 'snapshot.agent_fix.start', title: 'Started snapshot fix with agent' },
  'POST /v1/projects/:projectId/snapshots/rebuild': { action: 'snapshot.rebuild', title: 'Started sandbox snapshot rebuild' },
  'GET /v1/projects/:projectId/triggers': { action: 'trigger.list', title: 'Listed triggers' },
  'POST /v1/projects/:projectId/triggers': { action: 'trigger.create', title: 'Created trigger' },
  'DELETE /v1/projects/:projectId/triggers/:slug': { action: 'trigger.delete', title: 'Deleted trigger' },
  'PATCH /v1/projects/:projectId/triggers/:slug': { action: 'trigger.update', title: 'Updated trigger' },
  'POST /v1/projects/:projectId/triggers/:slug/fire': { action: 'trigger.fire', title: 'Fired trigger' },
  'PATCH /v1/projects/:projectId/triggers/activation': { action: 'trigger.activation.set', title: 'Paused or resumed all triggers' },
  'POST /v1/projects/:projectId/turn-question': { action: 'session.question.create', title: 'Submitted session question' },
  'POST /v1/projects/:projectId/turn-stream': { action: 'session.turn.stream', title: 'Streamed session turn' },
  'GET /v1/projects/:projectId/version-diff': { action: 'git.version_diff.read', title: 'Viewed version diff' },
  'POST /v1/projects/create-repo': { action: 'project.repository.create', title: 'Created project with new GitHub repository' },
  'GET /v1/projects/git/backend': { action: 'git.backend.read', title: 'Viewed instance Git backend' },
  'GET /v1/projects/git/backend/repositories': { action: 'git.backend.repository.list', title: 'Listed instance Git backend repositories' },
  'DELETE /v1/projects/github/installation': 'DELETE /v1/projects/github/installations/:installationId',
  'GET /v1/projects/github/installation': 'GET /v1/projects/github/installations',
  'POST /v1/projects/github/installation': { action: 'git.github.installation.connect', title: 'Connected GitHub installation' },
  'GET /v1/projects/github/installations': { action: 'git.github.installation.list', title: 'Listed GitHub installations' },
  'DELETE /v1/projects/github/installations/:installationId': { action: 'git.github.installation.disconnect', title: 'Disconnected GitHub installation' },
  'POST /v1/projects/github/installations/link': { action: 'git.github.installation.link', title: 'Linked existing GitHub installation' },
  'POST /v1/projects/github/installations/linkable': { action: 'git.github.installation.linkable.list', title: 'Listed linkable GitHub installations' },
  'GET /v1/projects/github/repositories': { action: 'git.github.repository.list', title: 'Listed GitHub repositories' },
  'GET /v1/projects/github/repository-branches': { action: 'git.github.repository.branch.list', title: 'Listed GitHub repository branches' },
  'POST /v1/projects/link-repository': { action: 'project.repository.link', title: 'Linked repository as project' },
  'GET /v1/projects/managed-git/status': { action: 'git.managed_status.read', title: 'Viewed managed Git status' },
  'POST /v1/projects/provision': { action: 'project.provision', title: 'Provisioned project' },
  'POST /v1/projects/provision-stream': 'POST /v1/projects/provision',
  'GET /v1/projects/suna-migration/eligibility': { action: 'project.suna_migration.eligibility.read', title: 'Viewed project migration eligibility' },
  'POST /v1/projects/suna-migration/start': { action: 'project.suna_migration.start', title: 'Started project migration' },
  'GET /v1/projects/suna-migration/status': { action: 'project.suna_migration.read', title: 'Viewed project migration status' },
  'GET /v1/public/session-shares/:shareId': { action: 'session.public_share.metadata.read', title: 'Viewed publicly shared session' },
  'GET /v1/public/session-shares/:shareId/messages': { action: 'session.public_share.message.list', title: 'Listed publicly shared session messages' },
  'POST /v1/router/chat/completions': { action: 'router.chat_completion.create', title: 'Generated chat completion' },
  'ALL /v1/router/context7': 'ALL /v1/router/context7/*',
  'ALL /v1/router/context7/*': { action: 'router.context7.proxy', title: 'Called Context7 through router' },
  'ALL /v1/router/firecrawl': 'ALL /v1/router/firecrawl/*',
  'ALL /v1/router/firecrawl/*': { action: 'router.firecrawl.proxy', title: 'Called Firecrawl through router' },
  'ALL /v1/router/gemini': 'ALL /v1/router/gemini/*',
  'ALL /v1/router/gemini/*': { action: 'router.gemini.proxy', title: 'Called Gemini through router' },
  'ALL /v1/router/groq': 'ALL /v1/router/groq/*',
  'ALL /v1/router/groq/*': { action: 'router.groq.proxy', title: 'Called Groq through router' },
  'GET /v1/router/health': { action: 'router.health.check', title: 'Checked router health' },
  'POST /v1/router/image-search': { action: 'router.image.search', title: 'Searched images' },
  'GET /v1/router/models': { action: 'router.model.list', title: 'Listed router models' },
  'GET /v1/router/models/:model': { action: 'router.model.read', title: 'Viewed router model' },
  'ALL /v1/router/openai': 'ALL /v1/router/openai/*',
  'ALL /v1/router/openai/*': { action: 'router.openai.proxy', title: 'Called OpenAI through router' },
  'ALL /v1/router/serper': 'ALL /v1/router/serper/*',
  'ALL /v1/router/serper/*': { action: 'router.serper.proxy', title: 'Called Serper through router' },
  'ALL /v1/router/tavily': 'ALL /v1/router/tavily/*',
  'ALL /v1/router/tavily/*': { action: 'router.tavily.proxy', title: 'Called Tavily through router' },
  'POST /v1/router/web-search': { action: 'router.web.search', title: 'Searched the web' },
  'ALL /v1/router/xai': 'ALL /v1/router/xai/*',
  'ALL /v1/router/xai/*': { action: 'router.xai.proxy', title: 'Called xAI through router' },
  'GET /v1/runtime-assets/agent': { action: 'runtime.agent.download', title: 'Downloaded sandbox agent' },
  'HEAD /v1/runtime-assets/agent': { action: 'runtime.agent.check', title: 'Checked sandbox agent' },
  'GET /v1/runtime-assets/cli': { action: 'runtime.cli.download', title: 'Downloaded sandbox CLI' },
  'HEAD /v1/runtime-assets/cli': { action: 'runtime.cli.check', title: 'Checked sandbox CLI' },
  'GET /v1/runtime-assets/entrypoint': { action: 'runtime.entrypoint.download', title: 'Downloaded sandbox entrypoint' },
  'HEAD /v1/runtime-assets/entrypoint': { action: 'runtime.entrypoint.check', title: 'Checked sandbox entrypoint' },
  'GET /v1/runtime-assets/managed-skills': { action: 'runtime.managed_skills.download', title: 'Downloaded managed skills' },
  'GET /v1/runtime-assets/manifest': { action: 'runtime.manifest.read', title: 'Checked sandbox runtime-asset versions' },
  'GET /v1/setup-links/connectors/:token': { action: 'connector.setup_link.read', title: 'Opened connector setup link' },
  'POST /v1/setup-links/connectors/:token/finalize': { action: 'connector.setup_link.finalize', title: 'Finished connector setup-link authorization' },
  'POST /v1/setup-links/connectors/:token/start': { action: 'connector.setup_link.start', title: 'Started connector setup-link authorization' },
  'GET /v1/setup-links/secret/:token': { action: 'secret.setup_link.read', title: 'Opened secret setup link' },
  'POST /v1/setup-links/secret/:token': { action: 'secret.setup_link.set', title: 'Saved secrets via setup link' },
  'POST /v1/setup/bootstrap-owner': { action: 'setup.owner.create', title: 'Created instance owner account' },
  'GET /v1/setup/health': { action: 'setup.health.read', title: 'Checked instance service health' },
  'GET /v1/setup/install-status': { action: 'setup.install_status.read', title: 'Viewed instance install status' },
  'GET /v1/setup/sandbox-providers': { action: 'setup.sandbox_provider.list', title: 'Listed enabled sandbox providers' },
  'POST /v1/setup/setup-complete': { action: 'setup.wizard.complete', title: 'Completed setup wizard' },
  'GET /v1/setup/setup-status': { action: 'setup.wizard.read', title: 'Viewed setup wizard status' },
  'GET /v1/setup/setup-wizard-step': { action: 'setup.wizard_step.read', title: 'Viewed setup wizard step' },
  'POST /v1/setup/setup-wizard-step': { action: 'setup.wizard_step.update', title: 'Updated setup wizard step' },
  'GET /v1/setup/status': { action: 'setup.system_status.read', title: 'Viewed instance system status' },
  'GET /v1/skills': { action: 'skill.system.list', title: 'Listed Kortix system skills' },
  'GET /v1/skills/:name': { action: 'skill.system.read', title: 'Viewed Kortix system skill' },
  'GET /v1/skills/:name/file': { action: 'skill.system.file.read', title: 'Viewed Kortix system skill file' },
  'POST /v1/system/demo-request': { action: 'system.demo_request.create', title: 'Submitted demo request' },
  'GET /v1/system/maintenance': { action: 'system.maintenance.read', title: 'Viewed maintenance config' },
  'PUT /v1/system/maintenance': { action: 'system.maintenance.update', title: 'Updated maintenance config' },
  'GET /v1/system/status': { action: 'system.status.read', title: 'Viewed system status banner' },
  'GET /v1/tunnel/audit/:tunnelId': { action: 'tunnel.audit_log.list', title: 'Viewed computer tunnel audit log' },
  'GET /v1/tunnel/connections': { action: 'tunnel.connection.list', title: 'Listed computer tunnels' },
  'POST /v1/tunnel/connections': { action: 'tunnel.connection.create', title: 'Registered computer tunnel' },
  'DELETE /v1/tunnel/connections/:tunnelId': { action: 'tunnel.connection.delete', title: 'Deleted computer tunnel' },
  'GET /v1/tunnel/connections/:tunnelId': { action: 'tunnel.connection.read', title: 'Viewed computer tunnel' },
  'PATCH /v1/tunnel/connections/:tunnelId': { action: 'tunnel.connection.update', title: 'Updated computer tunnel' },
  'POST /v1/tunnel/connections/:tunnelId/rotate-token': { action: 'tunnel.connection.token.rotate', title: 'Rotated computer tunnel setup token' },
  'POST /v1/tunnel/device-auth': { action: 'tunnel.device_auth.create', title: 'Requested computer tunnel device authorization' },
  'POST /v1/tunnel/device-auth/:code/approve': { action: 'tunnel.device_auth.approve', title: 'Approved computer tunnel device authorization' },
  'POST /v1/tunnel/device-auth/:code/deny': { action: 'tunnel.device_auth.deny', title: 'Denied computer tunnel device authorization' },
  'GET /v1/tunnel/device-auth/:code/info': { action: 'tunnel.device_auth.read', title: 'Viewed computer tunnel device authorization' },
  'GET /v1/tunnel/device-auth/:code/status': { action: 'tunnel.device_auth.check', title: 'Polled computer tunnel device authorization' },
  'GET /v1/tunnel/permission-requests': { action: 'tunnel.permission_request.list', title: 'Listed computer tunnel permission requests' },
  'POST /v1/tunnel/permission-requests/:requestId/approve': { action: 'tunnel.permission_request.approve', title: 'Approved computer tunnel permission request' },
  'POST /v1/tunnel/permission-requests/:requestId/deny': { action: 'tunnel.permission_request.deny', title: 'Denied computer tunnel permission request' },
  'GET /v1/tunnel/permission-requests/stream': { action: 'tunnel.event.stream', title: 'Streamed computer tunnel events' },
  'GET /v1/tunnel/permissions/:tunnelId': { action: 'tunnel.permission.list', title: 'Listed computer tunnel permissions' },
  'POST /v1/tunnel/permissions/:tunnelId': { action: 'tunnel.permission.grant', title: 'Granted computer tunnel permission' },
  'DELETE /v1/tunnel/permissions/:tunnelId/:permissionId': { action: 'tunnel.permission.revoke', title: 'Revoked computer tunnel permission' },
  'POST /v1/tunnel/rpc/:tunnelId': { action: 'tunnel.rpc.send', title: 'Sent operation to computer tunnel' },
  'GET /v1/usage': { action: 'usage.rollup.read', title: 'Viewed account usage rollup' },
  'GET /v1/usage/cost-by-project': { action: 'usage.project_cost.list', title: 'Viewed project cost rollup' },
  'GET /v1/usage/cost-summary': { action: 'usage.cost_summary.read', title: 'Viewed cost summary' },
  'GET /v1/usage/session-costs': { action: 'usage.session_cost.list', title: 'Listed session costs' },
  'GET /v1/usage/session-costs/:sessionId': { action: 'usage.session_cost.read', title: 'Viewed session cost ledger' },
  'GET /v1/user-roles': { action: 'auth.platform_role.read', title: 'Viewed own platform role' },
  'POST /v1/webhooks/auth/send-email': { action: 'webhook.supabase_auth.send_email.receive', title: 'Received auth email hook' },
  'POST /v1/webhooks/email/agentmail': { action: 'webhook.agentmail.message.receive', title: 'Received AgentMail inbound email' },
  'POST /v1/webhooks/projects/:projectId/:slug': { action: 'webhook.trigger.receive', title: 'Received trigger webhook' },
  'POST /v1/webhooks/sandbox/daytona': { action: 'webhook.daytona.sandbox_lifecycle.receive', title: 'Received Daytona sandbox lifecycle event' },
  'POST /v1/webhooks/sandbox/platinum': { action: 'webhook.platinum.sandbox_lifecycle.receive', title: 'Received Platinum sandbox lifecycle event' },
  'POST /v1/webhooks/slack': { action: 'webhook.slack.event.receive', title: 'Received Slack event' },
  'POST /v1/webhooks/slack/:projectId': { action: 'webhook.slack.custom_app.event.receive', title: 'Received custom Slack app event' },
  'POST /v1/webhooks/slack/:projectId/commands': { action: 'webhook.slack.custom_app.command.receive', title: 'Received custom Slack app slash command' },
  'POST /v1/webhooks/slack/:projectId/interactivity': { action: 'webhook.slack.custom_app.interaction.receive', title: 'Received custom Slack app interaction' },
  'GET /v1/webhooks/slack/:projectId/manifest': { action: 'channel.slack.custom_app_manifest.read', title: 'Viewed custom Slack app manifest' },
  'POST /v1/webhooks/slack/commands': { action: 'webhook.slack.command.receive', title: 'Received Slack slash command' },
  'POST /v1/webhooks/slack/interactivity': { action: 'webhook.slack.interaction.receive', title: 'Received Slack interaction' },
  'GET /v1/webhooks/slack/oauth/callback': { action: 'channel.slack.install.complete', title: 'Completed Slack app installation' },
  'POST /v1/webhooks/teams/:projectId/messages': { action: 'webhook.teams.custom_app.activity.receive', title: 'Received custom Teams app activity' },
  'POST /v1/webhooks/teams/messages': { action: 'webhook.teams.activity.receive', title: 'Received Teams activity' },
  'GET /v1/webhooks/teams/oauth/callback': { action: 'channel.teams.install.complete', title: 'Completed Teams app installation' },
  'POST /v1/webhooks/telegram/:projectId': { action: 'webhook.telegram.update.receive', title: 'Received Telegram update' },
  'ENTRY app_origin': { action: 'app.origin.access', title: 'Opened deployed Kortix App' },
  'ENTRY app_origin:websocket': { action: 'app.origin.websocket.connect', title: 'Opened Kortix App WebSocket' },
  'ENTRY preview_origin': { action: 'sandbox.preview.access', title: 'Opened sandbox preview' },
  'ENTRY preview_origin:websocket': { action: 'sandbox.preview.websocket.connect', title: 'Opened sandbox preview WebSocket' },
  'ENTRY ws:/v1/p/:sandboxId/:port/*': { action: 'sandbox.port.websocket.connect', title: 'Opened sandbox port WebSocket' },
  'ENTRY ws:/v1/tunnel/ws': { action: 'tunnel.agent.connect', title: 'Connected computer tunnel agent' },
};
