/**
 * The app icon registry — the ONLY module that imports `phosphor-react-native`.
 *
 * Each glyph is imported from its own file: Metro tree shaking is off in this
 * app, so the package barrel would ship all 1,512 icons × 6 weights. This list
 * IS the icon bundle, and `icon-imports.test.ts` fails when an export has no
 * consumer. Every export is bound to `DEFAULT_ICON_WEIGHT` (see bind.tsx).
 *
 * To add an icon: add its import + export pair here (alphabetical), then
 * import it from `@/lib/icons` at the call site.
 */
import { ArchiveIcon as ArchiveGlyph } from 'phosphor-react-native/src/icons/Archive';
import { ArrowClockwiseIcon as ArrowClockwiseGlyph } from 'phosphor-react-native/src/icons/ArrowClockwise';
import { ArrowCounterClockwiseIcon as ArrowCounterClockwiseGlyph } from 'phosphor-react-native/src/icons/ArrowCounterClockwise';
import { ArrowDownIcon as ArrowDownGlyph } from 'phosphor-react-native/src/icons/ArrowDown';
import { ArrowElbowDownRightIcon as ArrowElbowDownRightGlyph } from 'phosphor-react-native/src/icons/ArrowElbowDownRight';
import { ArrowElbowLeftUpIcon as ArrowElbowLeftUpGlyph } from 'phosphor-react-native/src/icons/ArrowElbowLeftUp';
import { ArrowLeftIcon as ArrowLeftGlyph } from 'phosphor-react-native/src/icons/ArrowLeft';
import { ArrowRightIcon as ArrowRightGlyph } from 'phosphor-react-native/src/icons/ArrowRight';
import { ArrowSquareOutIcon as ArrowSquareOutGlyph } from 'phosphor-react-native/src/icons/ArrowSquareOut';
import { ArrowUUpLeftIcon as ArrowUUpLeftGlyph } from 'phosphor-react-native/src/icons/ArrowUUpLeft';
import { ArrowUpIcon as ArrowUpGlyph } from 'phosphor-react-native/src/icons/ArrowUp';
import { ArrowUpRightIcon as ArrowUpRightGlyph } from 'phosphor-react-native/src/icons/ArrowUpRight';
import { ArrowsDownUpIcon as ArrowsDownUpGlyph } from 'phosphor-react-native/src/icons/ArrowsDownUp';
import { ArrowsInSimpleIcon as ArrowsInSimpleGlyph } from 'phosphor-react-native/src/icons/ArrowsInSimple';
import { ArrowsLeftRightIcon as ArrowsLeftRightGlyph } from 'phosphor-react-native/src/icons/ArrowsLeftRight';
import { ArrowsOutSimpleIcon as ArrowsOutSimpleGlyph } from 'phosphor-react-native/src/icons/ArrowsOutSimple';
import { BellIcon as BellGlyph } from 'phosphor-react-native/src/icons/Bell';
import { BellSlashIcon as BellSlashGlyph } from 'phosphor-react-native/src/icons/BellSlash';
import { BookOpenIcon as BookOpenGlyph } from 'phosphor-react-native/src/icons/BookOpen';
import { BrainIcon as BrainGlyph } from 'phosphor-react-native/src/icons/Brain';
import { BuildingsIcon as BuildingsGlyph } from 'phosphor-react-native/src/icons/Buildings';
import { CalendarDotsIcon as CalendarDotsGlyph } from 'phosphor-react-native/src/icons/CalendarDots';
import { CalendarIcon as CalendarGlyph } from 'phosphor-react-native/src/icons/Calendar';
import { CameraIcon as CameraGlyph } from 'phosphor-react-native/src/icons/Camera';
import { CaretDownIcon as CaretDownGlyph } from 'phosphor-react-native/src/icons/CaretDown';
import { CaretLeftIcon as CaretLeftGlyph } from 'phosphor-react-native/src/icons/CaretLeft';
import { CaretRightIcon as CaretRightGlyph } from 'phosphor-react-native/src/icons/CaretRight';
import { CaretUpDownIcon as CaretUpDownGlyph } from 'phosphor-react-native/src/icons/CaretUpDown';
import { CaretUpIcon as CaretUpGlyph } from 'phosphor-react-native/src/icons/CaretUp';
import { CertificateIcon as CertificateGlyph } from 'phosphor-react-native/src/icons/Certificate';
import { ChartBarIcon as ChartBarGlyph } from 'phosphor-react-native/src/icons/ChartBar';
import { ChartLineIcon as ChartLineGlyph } from 'phosphor-react-native/src/icons/ChartLine';
import { ChatCircleDotsIcon as ChatCircleDotsGlyph } from 'phosphor-react-native/src/icons/ChatCircleDots';
import { ChatCircleIcon as ChatCircleGlyph } from 'phosphor-react-native/src/icons/ChatCircle';
import { ChatIcon as ChatGlyph } from 'phosphor-react-native/src/icons/Chat';
import { ChatsTeardropIcon as ChatsTeardropGlyph } from 'phosphor-react-native/src/icons/ChatsTeardrop';
import { CheckCircleIcon as CheckCircleGlyph } from 'phosphor-react-native/src/icons/CheckCircle';
import { CheckIcon as CheckGlyph } from 'phosphor-react-native/src/icons/Check';
import { CheckSquareIcon as CheckSquareGlyph } from 'phosphor-react-native/src/icons/CheckSquare';
import { CircleDashedIcon as CircleDashedGlyph } from 'phosphor-react-native/src/icons/CircleDashed';
import { CircleIcon as CircleGlyph } from 'phosphor-react-native/src/icons/Circle';
import { ClockCounterClockwiseIcon as ClockCounterClockwiseGlyph } from 'phosphor-react-native/src/icons/ClockCounterClockwise';
import { ClockIcon as ClockGlyph } from 'phosphor-react-native/src/icons/Clock';
import { CodeIcon as CodeGlyph } from 'phosphor-react-native/src/icons/Code';
import { CodeSimpleIcon as CodeSimpleGlyph } from 'phosphor-react-native/src/icons/CodeSimple';
import { CpuIcon as CpuGlyph } from 'phosphor-react-native/src/icons/Cpu';
import { CreditCardIcon as CreditCardGlyph } from 'phosphor-react-native/src/icons/CreditCard';
import { CrownIcon as CrownGlyph } from 'phosphor-react-native/src/icons/Crown';
import { CubeIcon as CubeGlyph } from 'phosphor-react-native/src/icons/Cube';
import { DatabaseIcon as DatabaseGlyph } from 'phosphor-react-native/src/icons/Database';
import { DesktopIcon as DesktopGlyph } from 'phosphor-react-native/src/icons/Desktop';
import { DeviceMobileIcon as DeviceMobileGlyph } from 'phosphor-react-native/src/icons/DeviceMobile';
import { DotsThreeCircleIcon as DotsThreeCircleGlyph } from 'phosphor-react-native/src/icons/DotsThreeCircle';
import { DotsThreeIcon as DotsThreeGlyph } from 'phosphor-react-native/src/icons/DotsThree';
import { DotsThreeOutlineIcon as DotsThreeOutlineGlyph } from 'phosphor-react-native/src/icons/DotsThreeOutline';
import { DotsThreeVerticalIcon as DotsThreeVerticalGlyph } from 'phosphor-react-native/src/icons/DotsThreeVertical';
import { DownloadIcon as DownloadGlyph } from 'phosphor-react-native/src/icons/Download';
import { DownloadSimpleIcon as DownloadSimpleGlyph } from 'phosphor-react-native/src/icons/DownloadSimple';
import { EnvelopeIcon as EnvelopeGlyph } from 'phosphor-react-native/src/icons/Envelope';
import { ExportIcon as ExportGlyph } from 'phosphor-react-native/src/icons/Export';
import { EyeIcon as EyeGlyph } from 'phosphor-react-native/src/icons/Eye';
import { EyeSlashIcon as EyeSlashGlyph } from 'phosphor-react-native/src/icons/EyeSlash';
import { EyeglassesIcon as EyeglassesGlyph } from 'phosphor-react-native/src/icons/Eyeglasses';
import { FileArchiveIcon as FileArchiveGlyph } from 'phosphor-react-native/src/icons/FileArchive';
import { FileAudioIcon as FileAudioGlyph } from 'phosphor-react-native/src/icons/FileAudio';
import { FileCodeIcon as FileCodeGlyph } from 'phosphor-react-native/src/icons/FileCode';
import { FileCsvIcon as FileCsvGlyph } from 'phosphor-react-native/src/icons/FileCsv';
import { FileDashedIcon as FileDashedGlyph } from 'phosphor-react-native/src/icons/FileDashed';
import { FileDocIcon as FileDocGlyph } from 'phosphor-react-native/src/icons/FileDoc';
import { FileHtmlIcon as FileHtmlGlyph } from 'phosphor-react-native/src/icons/FileHtml';
import { FileIcon as FileGlyph } from 'phosphor-react-native/src/icons/File';
import { FileImageIcon as FileImageGlyph } from 'phosphor-react-native/src/icons/FileImage';
import { FileLockIcon as FileLockGlyph } from 'phosphor-react-native/src/icons/FileLock';
import { FileMagnifyingGlassIcon as FileMagnifyingGlassGlyph } from 'phosphor-react-native/src/icons/FileMagnifyingGlass';
import { FileMdIcon as FileMdGlyph } from 'phosphor-react-native/src/icons/FileMd';
import { FileTsIcon as FileTsGlyph } from 'phosphor-react-native/src/icons/FileTs';
import { FileTsxIcon as FileTsxGlyph } from 'phosphor-react-native/src/icons/FileTsx';
import { FileJsIcon as FileJsGlyph } from 'phosphor-react-native/src/icons/FileJs';
import { FileJsxIcon as FileJsxGlyph } from 'phosphor-react-native/src/icons/FileJsx';
import { FileCssIcon as FileCssGlyph } from 'phosphor-react-native/src/icons/FileCss';
import { FilePyIcon as FilePyGlyph } from 'phosphor-react-native/src/icons/FilePy';
import { FileRsIcon as FileRsGlyph } from 'phosphor-react-native/src/icons/FileRs';
import { FileCIcon as FileCGlyph } from 'phosphor-react-native/src/icons/FileC';
import { FileCppIcon as FileCppGlyph } from 'phosphor-react-native/src/icons/FileCpp';
import { FileVueIcon as FileVueGlyph } from 'phosphor-react-native/src/icons/FileVue';
import { FileSqlIcon as FileSqlGlyph } from 'phosphor-react-native/src/icons/FileSql';
import { FilePngIcon as FilePngGlyph } from 'phosphor-react-native/src/icons/FilePng';
import { FileJpgIcon as FileJpgGlyph } from 'phosphor-react-native/src/icons/FileJpg';
import { FileTxtIcon as FileTxtGlyph } from 'phosphor-react-native/src/icons/FileTxt';
import { FileIniIcon as FileIniGlyph } from 'phosphor-react-native/src/icons/FileIni';
import { FileMinusIcon as FileMinusGlyph } from 'phosphor-react-native/src/icons/FileMinus';
import { FilePdfIcon as FilePdfGlyph } from 'phosphor-react-native/src/icons/FilePdf';
import { FilePlusIcon as FilePlusGlyph } from 'phosphor-react-native/src/icons/FilePlus';
import { FilePptIcon as FilePptGlyph } from 'phosphor-react-native/src/icons/FilePpt';
import { FileSvgIcon as FileSvgGlyph } from 'phosphor-react-native/src/icons/FileSvg';
import { FileTextIcon as FileTextGlyph } from 'phosphor-react-native/src/icons/FileText';
import { FileVideoIcon as FileVideoGlyph } from 'phosphor-react-native/src/icons/FileVideo';
import { FileXIcon as FileXGlyph } from 'phosphor-react-native/src/icons/FileX';
import { FileXlsIcon as FileXlsGlyph } from 'phosphor-react-native/src/icons/FileXls';
import { FileZipIcon as FileZipGlyph } from 'phosphor-react-native/src/icons/FileZip';
import { FilesIcon as FilesGlyph } from 'phosphor-react-native/src/icons/Files';
import { FingerprintIcon as FingerprintGlyph } from 'phosphor-react-native/src/icons/Fingerprint';
import { FlaskIcon as FlaskGlyph } from 'phosphor-react-native/src/icons/Flask';
import { FloppyDiskIcon as FloppyDiskGlyph } from 'phosphor-react-native/src/icons/FloppyDisk';
import { FolderIcon as FolderGlyph } from 'phosphor-react-native/src/icons/Folder';
import { FolderOpenIcon as FolderOpenGlyph } from 'phosphor-react-native/src/icons/FolderOpen';
import { FolderPlusIcon as FolderPlusGlyph } from 'phosphor-react-native/src/icons/FolderPlus';
import { FunnelIcon as FunnelGlyph } from 'phosphor-react-native/src/icons/Funnel';
import { GearSixIcon as GearSixGlyph } from 'phosphor-react-native/src/icons/GearSix';
import { GitBranchIcon as GitBranchGlyph } from 'phosphor-react-native/src/icons/GitBranch';
import { GitCommitIcon as GitCommitGlyph } from 'phosphor-react-native/src/icons/GitCommit';
import { GitDiffIcon as GitDiffGlyph } from 'phosphor-react-native/src/icons/GitDiff';
import { GitPullRequestIcon as GitPullRequestGlyph } from 'phosphor-react-native/src/icons/GitPullRequest';
import { GithubLogoIcon as GithubLogoGlyph } from 'phosphor-react-native/src/icons/GithubLogo';
import { GlobeIcon as GlobeGlyph } from 'phosphor-react-native/src/icons/Globe';
import { HammerIcon as HammerGlyph } from 'phosphor-react-native/src/icons/Hammer';
import { HardDrivesIcon as HardDrivesGlyph } from 'phosphor-react-native/src/icons/HardDrives';
import { HashIcon as HashGlyph } from 'phosphor-react-native/src/icons/Hash';
import { HeadphonesIcon as HeadphonesGlyph } from 'phosphor-react-native/src/icons/Headphones';
import { HeartIcon as HeartGlyph } from 'phosphor-react-native/src/icons/Heart';
import { HouseIcon as HouseGlyph } from 'phosphor-react-native/src/icons/House';
import { ImageIcon as ImageGlyph } from 'phosphor-react-native/src/icons/Image';
import { InfinityIcon as InfinityGlyph } from 'phosphor-react-native/src/icons/Infinity';
import { InfoIcon as InfoGlyph } from 'phosphor-react-native/src/icons/Info';
import { KanbanIcon as KanbanGlyph } from 'phosphor-react-native/src/icons/Kanban';
import { KeyIcon as KeyGlyph } from 'phosphor-react-native/src/icons/Key';
import { LifebuoyIcon as LifebuoyGlyph } from 'phosphor-react-native/src/icons/Lifebuoy';
import { LightbulbIcon as LightbulbGlyph } from 'phosphor-react-native/src/icons/Lightbulb';
import { LightningIcon as LightningGlyph } from 'phosphor-react-native/src/icons/Lightning';
import { LinkBreakIcon as LinkBreakGlyph } from 'phosphor-react-native/src/icons/LinkBreak';
import { LinkSimpleIcon as LinkSimpleGlyph } from 'phosphor-react-native/src/icons/LinkSimple';
import { ListChecksIcon as ListChecksGlyph } from 'phosphor-react-native/src/icons/ListChecks';
import { ListIcon as ListGlyph } from 'phosphor-react-native/src/icons/List';
import { LockIcon as LockGlyph } from 'phosphor-react-native/src/icons/Lock';
import { LockOpenIcon as LockOpenGlyph } from 'phosphor-react-native/src/icons/LockOpen';
import { MagnifyingGlassIcon as MagnifyingGlassGlyph } from 'phosphor-react-native/src/icons/MagnifyingGlass';
import { MinusIcon as MinusGlyph } from 'phosphor-react-native/src/icons/Minus';
import { MonitorIcon as MonitorGlyph } from 'phosphor-react-native/src/icons/Monitor';
import { MonitorPlayIcon as MonitorPlayGlyph } from 'phosphor-react-native/src/icons/MonitorPlay';
import { MoonIcon as MoonGlyph } from 'phosphor-react-native/src/icons/Moon';
import { MusicNotesIcon as MusicNotesGlyph } from 'phosphor-react-native/src/icons/MusicNotes';
import { NavigationArrowIcon as NavigationArrowGlyph } from 'phosphor-react-native/src/icons/NavigationArrow';
import { NetworkIcon as NetworkGlyph } from 'phosphor-react-native/src/icons/Network';
import { NotePencilIcon as NotePencilGlyph } from 'phosphor-react-native/src/icons/NotePencil';
import { PaletteIcon as PaletteGlyph } from 'phosphor-react-native/src/icons/Palette';
import { PaperPlaneTiltIcon as PaperPlaneTiltGlyph } from 'phosphor-react-native/src/icons/PaperPlaneTilt';
import { PaperclipIcon as PaperclipGlyph } from 'phosphor-react-native/src/icons/Paperclip';
import { PauseIcon as PauseGlyph } from 'phosphor-react-native/src/icons/Pause';
import { PencilIcon as PencilGlyph } from 'phosphor-react-native/src/icons/Pencil';
import { PencilSimpleIcon as PencilSimpleGlyph } from 'phosphor-react-native/src/icons/PencilSimple';
import { PhoneIcon as PhoneGlyph } from 'phosphor-react-native/src/icons/Phone';
import { PhoneSlashIcon as PhoneSlashGlyph } from 'phosphor-react-native/src/icons/PhoneSlash';
import { PlayIcon as PlayGlyph } from 'phosphor-react-native/src/icons/Play';
import { PlugIcon as PlugGlyph } from 'phosphor-react-native/src/icons/Plug';
import { PlusIcon as PlusGlyph } from 'phosphor-react-native/src/icons/Plus';
import { PresentationIcon as PresentationGlyph } from 'phosphor-react-native/src/icons/Presentation';
import { ProhibitIcon as ProhibitGlyph } from 'phosphor-react-native/src/icons/Prohibit';
import { PulseIcon as PulseGlyph } from 'phosphor-react-native/src/icons/Pulse';
import { QuestionIcon as QuestionGlyph } from 'phosphor-react-native/src/icons/Question';
import { RadioButtonIcon as RadioButtonGlyph } from 'phosphor-react-native/src/icons/RadioButton';
import { ReadCvLogoIcon as ReadCvLogoGlyph } from 'phosphor-react-native/src/icons/ReadCvLogo';
import { RepeatIcon as RepeatGlyph } from 'phosphor-react-native/src/icons/Repeat';
import { RobotIcon as RobotGlyph } from 'phosphor-react-native/src/icons/Robot';
import { RocketIcon as RocketGlyph } from 'phosphor-react-native/src/icons/Rocket';
import { ScissorsIcon as ScissorsGlyph } from 'phosphor-react-native/src/icons/Scissors';
import { SealCheckIcon as SealCheckGlyph } from 'phosphor-react-native/src/icons/SealCheck';
import { ShieldCheckIcon as ShieldCheckGlyph } from 'phosphor-react-native/src/icons/ShieldCheck';
import { ShieldIcon as ShieldGlyph } from 'phosphor-react-native/src/icons/Shield';
import { ShieldWarningIcon as ShieldWarningGlyph } from 'phosphor-react-native/src/icons/ShieldWarning';
import { SignOutIcon as SignOutGlyph } from 'phosphor-react-native/src/icons/SignOut';
import { SlackLogoIcon as SlackLogoGlyph } from 'phosphor-react-native/src/icons/SlackLogo';
import { SlidersHorizontalIcon as SlidersHorizontalGlyph } from 'phosphor-react-native/src/icons/SlidersHorizontal';
import { SortAscendingIcon as SortAscendingGlyph } from 'phosphor-react-native/src/icons/SortAscending';
import { SparkleIcon as SparkleGlyph } from 'phosphor-react-native/src/icons/Sparkle';
import { SpeakerHighIcon as SpeakerHighGlyph } from 'phosphor-react-native/src/icons/SpeakerHigh';
import { SquareIcon as SquareGlyph } from 'phosphor-react-native/src/icons/Square';
import { SquaresFourIcon as SquaresFourGlyph } from 'phosphor-react-native/src/icons/SquaresFour';
import { StackIcon as StackGlyph } from 'phosphor-react-native/src/icons/Stack';
import { StarIcon as StarGlyph } from 'phosphor-react-native/src/icons/Star';
import { StopCircleIcon as StopCircleGlyph } from 'phosphor-react-native/src/icons/StopCircle';
import { SunIcon as SunGlyph } from 'phosphor-react-native/src/icons/Sun';
import { TableIcon as TableGlyph } from 'phosphor-react-native/src/icons/Table';
import { TagIcon as TagGlyph } from 'phosphor-react-native/src/icons/Tag';
import { TargetIcon as TargetGlyph } from 'phosphor-react-native/src/icons/Target';
import { TerminalIcon as TerminalGlyph } from 'phosphor-react-native/src/icons/Terminal';
import { TerminalWindowIcon as TerminalWindowGlyph } from 'phosphor-react-native/src/icons/TerminalWindow';
import { TextTIcon as TextTGlyph } from 'phosphor-react-native/src/icons/TextT';
import { TimerIcon as TimerGlyph } from 'phosphor-react-native/src/icons/Timer';
import { TrashIcon as TrashGlyph } from 'phosphor-react-native/src/icons/Trash';
import { TreeStructureIcon as TreeStructureGlyph } from 'phosphor-react-native/src/icons/TreeStructure';
import { UploadIcon as UploadGlyph } from 'phosphor-react-native/src/icons/Upload';
import { UserIcon as UserGlyph } from 'phosphor-react-native/src/icons/User';
import { UserPlusIcon as UserPlusGlyph } from 'phosphor-react-native/src/icons/UserPlus';
import { UsersIcon as UsersGlyph } from 'phosphor-react-native/src/icons/Users';
import { UsersThreeIcon as UsersThreeGlyph } from 'phosphor-react-native/src/icons/UsersThree';
import { VibrateIcon as VibrateGlyph } from 'phosphor-react-native/src/icons/Vibrate';
import { VideoIcon as VideoGlyph } from 'phosphor-react-native/src/icons/Video';
import { WalletIcon as WalletGlyph } from 'phosphor-react-native/src/icons/Wallet';
import { WarningCircleIcon as WarningCircleGlyph } from 'phosphor-react-native/src/icons/WarningCircle';
import { WarningIcon as WarningGlyph } from 'phosphor-react-native/src/icons/Warning';
import { WebhooksLogoIcon as WebhooksLogoGlyph } from 'phosphor-react-native/src/icons/WebhooksLogo';
import { WifiHighIcon as WifiHighGlyph } from 'phosphor-react-native/src/icons/WifiHigh';
import { WifiSlashIcon as WifiSlashGlyph } from 'phosphor-react-native/src/icons/WifiSlash';
import { WrenchIcon as WrenchGlyph } from 'phosphor-react-native/src/icons/Wrench';
import { XCircleIcon as XCircleGlyph } from 'phosphor-react-native/src/icons/XCircle';
import { XIcon as XGlyph } from 'phosphor-react-native/src/icons/X';

import { withAppWeight, withFixedWeight } from './bind';

export const ArchiveIcon = withAppWeight(ArchiveGlyph, 'ArchiveIcon');
export const ArrowClockwiseIcon = withAppWeight(ArrowClockwiseGlyph, 'ArrowClockwiseIcon');
export const ArrowCounterClockwiseIcon = withAppWeight(ArrowCounterClockwiseGlyph, 'ArrowCounterClockwiseIcon');
export const ArrowDownIcon = withAppWeight(ArrowDownGlyph, 'ArrowDownIcon');
export const ArrowElbowDownRightIcon = withAppWeight(
  ArrowElbowDownRightGlyph,
  'ArrowElbowDownRightIcon'
);
export const ArrowElbowLeftUpIcon = withAppWeight(ArrowElbowLeftUpGlyph, 'ArrowElbowLeftUpIcon');
export const ArrowLeftIcon = withAppWeight(ArrowLeftGlyph, 'ArrowLeftIcon');
export const ArrowRightIcon = withAppWeight(ArrowRightGlyph, 'ArrowRightIcon');
export const ArrowSquareOutIcon = withAppWeight(ArrowSquareOutGlyph, 'ArrowSquareOutIcon');
export const ArrowUUpLeftIcon = withAppWeight(ArrowUUpLeftGlyph, 'ArrowUUpLeftIcon');
export const ArrowUpIcon = withAppWeight(ArrowUpGlyph, 'ArrowUpIcon');
export const ArrowUpRightIcon = withAppWeight(ArrowUpRightGlyph, 'ArrowUpRightIcon');
export const ArrowsDownUpIcon = withAppWeight(ArrowsDownUpGlyph, 'ArrowsDownUpIcon');
export const ArrowsInSimpleIcon = withAppWeight(ArrowsInSimpleGlyph, 'ArrowsInSimpleIcon');
export const ArrowsLeftRightIcon = withAppWeight(ArrowsLeftRightGlyph, 'ArrowsLeftRightIcon');
export const ArrowsOutSimpleIcon = withAppWeight(ArrowsOutSimpleGlyph, 'ArrowsOutSimpleIcon');
export const BellIcon = withAppWeight(BellGlyph, 'BellIcon');
export const BellSlashIcon = withAppWeight(BellSlashGlyph, 'BellSlashIcon');
export const BookOpenIcon = withAppWeight(BookOpenGlyph, 'BookOpenIcon');
export const BrainIcon = withAppWeight(BrainGlyph, 'BrainIcon');
export const BuildingsIcon = withAppWeight(BuildingsGlyph, 'BuildingsIcon');
export const CalendarDotsIcon = withAppWeight(CalendarDotsGlyph, 'CalendarDotsIcon');
export const CalendarIcon = withAppWeight(CalendarGlyph, 'CalendarIcon');
export const CameraIcon = withAppWeight(CameraGlyph, 'CameraIcon');
export const CaretDownIcon = withAppWeight(CaretDownGlyph, 'CaretDownIcon');
export const CaretLeftIcon = withAppWeight(CaretLeftGlyph, 'CaretLeftIcon');
export const CaretRightIcon = withAppWeight(CaretRightGlyph, 'CaretRightIcon');
export const CaretUpDownIcon = withAppWeight(CaretUpDownGlyph, 'CaretUpDownIcon');
export const CaretUpIcon = withAppWeight(CaretUpGlyph, 'CaretUpIcon');
export const CertificateIcon = withAppWeight(CertificateGlyph, 'CertificateIcon');
export const ChartBarIcon = withAppWeight(ChartBarGlyph, 'ChartBarIcon');
export const ChartLineIcon = withAppWeight(ChartLineGlyph, 'ChartLineIcon');
export const ChatCircleDotsIcon = withAppWeight(ChatCircleDotsGlyph, 'ChatCircleDotsIcon');
export const ChatCircleIcon = withAppWeight(ChatCircleGlyph, 'ChatCircleIcon');
export const ChatIcon = withAppWeight(ChatGlyph, 'ChatIcon');
export const ChatsTeardropIcon = withAppWeight(ChatsTeardropGlyph, 'ChatsTeardropIcon');
export const CheckCircleIcon = withAppWeight(CheckCircleGlyph, 'CheckCircleIcon');
export const CheckIcon = withAppWeight(CheckGlyph, 'CheckIcon');
export const CheckSquareIcon = withAppWeight(CheckSquareGlyph, 'CheckSquareIcon');
export const CircleDashedIcon = withAppWeight(CircleDashedGlyph, 'CircleDashedIcon');
export const CircleIcon = withAppWeight(CircleGlyph, 'CircleIcon');
export const ClockCounterClockwiseIcon = withAppWeight(ClockCounterClockwiseGlyph, 'ClockCounterClockwiseIcon');
export const ClockIcon = withAppWeight(ClockGlyph, 'ClockIcon');
export const CodeIcon = withAppWeight(CodeGlyph, 'CodeIcon');
export const CodeSimpleIcon = withAppWeight(CodeSimpleGlyph, 'CodeSimpleIcon');
// Tiles glyph drawn by hand for the drawer's Connectors row; Phosphor has no match.
export { KortixConnectorsIcon as ConnectorsIcon } from './connectors';
// Web's own copy glyph (apps/web src/features/icon/icons/copy.tsx), not Phosphor's Copy.
export { KortixCopyIcon as CopyIcon } from './kortix-copy';
export const CpuIcon = withAppWeight(CpuGlyph, 'CpuIcon');
export const CreditCardIcon = withAppWeight(CreditCardGlyph, 'CreditCardIcon');
export const CrownIcon = withAppWeight(CrownGlyph, 'CrownIcon');
export const CubeIcon = withAppWeight(CubeGlyph, 'CubeIcon');
export const DatabaseIcon = withAppWeight(DatabaseGlyph, 'DatabaseIcon');
export const DesktopIcon = withAppWeight(DesktopGlyph, 'DesktopIcon');
export const DeviceMobileIcon = withAppWeight(DeviceMobileGlyph, 'DeviceMobileIcon');
export const DotsThreeCircleIcon = withAppWeight(DotsThreeCircleGlyph, 'DotsThreeCircleIcon');
export const DotsThreeIcon = withAppWeight(DotsThreeGlyph, 'DotsThreeIcon');
export const DotsThreeOutlineIcon = withAppWeight(DotsThreeOutlineGlyph, 'DotsThreeOutlineIcon');
export const DotsThreeVerticalIcon = withAppWeight(DotsThreeVerticalGlyph, 'DotsThreeVerticalIcon');
export const DownloadIcon = withAppWeight(DownloadGlyph, 'DownloadIcon');
export const DownloadSimpleIcon = withAppWeight(DownloadSimpleGlyph, 'DownloadSimpleIcon');
export const EnvelopeIcon = withAppWeight(EnvelopeGlyph, 'EnvelopeIcon');
export const ExportIcon = withAppWeight(ExportGlyph, 'ExportIcon');
export const EyeIcon = withAppWeight(EyeGlyph, 'EyeIcon');
export const EyeSlashIcon = withAppWeight(EyeSlashGlyph, 'EyeSlashIcon');
export const EyeglassesIcon = withAppWeight(EyeglassesGlyph, 'EyeglassesIcon');
export const FileArchiveIcon = withAppWeight(FileArchiveGlyph, 'FileArchiveIcon');
export const FileAudioIcon = withAppWeight(FileAudioGlyph, 'FileAudioIcon');
export const FileCodeIcon = withAppWeight(FileCodeGlyph, 'FileCodeIcon');
export const FileCsvIcon = withAppWeight(FileCsvGlyph, 'FileCsvIcon');
export const FileDashedIcon = withAppWeight(FileDashedGlyph, 'FileDashedIcon');
export const FileDocIcon = withAppWeight(FileDocGlyph, 'FileDocIcon');
export const FileHtmlIcon = withAppWeight(FileHtmlGlyph, 'FileHtmlIcon');
export const FileIcon = withAppWeight(FileGlyph, 'FileIcon');
export const FileImageIcon = withAppWeight(FileImageGlyph, 'FileImageIcon');
export const FileLockIcon = withAppWeight(FileLockGlyph, 'FileLockIcon');
export const FileMagnifyingGlassIcon = withAppWeight(FileMagnifyingGlassGlyph, 'FileMagnifyingGlassIcon');
export const FileMdIcon = withAppWeight(FileMdGlyph, 'FileMdIcon');
export const FileTsIcon = withAppWeight(FileTsGlyph, 'FileTsIcon');
export const FileTsxIcon = withAppWeight(FileTsxGlyph, 'FileTsxIcon');
export const FileJsIcon = withAppWeight(FileJsGlyph, 'FileJsIcon');
export const FileJsxIcon = withAppWeight(FileJsxGlyph, 'FileJsxIcon');
export const FileCssIcon = withAppWeight(FileCssGlyph, 'FileCssIcon');
export const FilePyIcon = withAppWeight(FilePyGlyph, 'FilePyIcon');
export const FileRsIcon = withAppWeight(FileRsGlyph, 'FileRsIcon');
export const FileCIcon = withAppWeight(FileCGlyph, 'FileCIcon');
export const FileCppIcon = withAppWeight(FileCppGlyph, 'FileCppIcon');
export const FileVueIcon = withAppWeight(FileVueGlyph, 'FileVueIcon');
export const FileSqlIcon = withAppWeight(FileSqlGlyph, 'FileSqlIcon');
export const FilePngIcon = withAppWeight(FilePngGlyph, 'FilePngIcon');
export const FileJpgIcon = withAppWeight(FileJpgGlyph, 'FileJpgIcon');
export const FileTxtIcon = withAppWeight(FileTxtGlyph, 'FileTxtIcon');
export const FileIniIcon = withAppWeight(FileIniGlyph, 'FileIniIcon');
export const FileMinusIcon = withAppWeight(FileMinusGlyph, 'FileMinusIcon');
export const FilePdfIcon = withAppWeight(FilePdfGlyph, 'FilePdfIcon');
export const FilePlusIcon = withAppWeight(FilePlusGlyph, 'FilePlusIcon');
export const FilePptIcon = withAppWeight(FilePptGlyph, 'FilePptIcon');
export const FileSvgIcon = withAppWeight(FileSvgGlyph, 'FileSvgIcon');
export const FileTextIcon = withAppWeight(FileTextGlyph, 'FileTextIcon');
export const FileVideoIcon = withAppWeight(FileVideoGlyph, 'FileVideoIcon');
export const FileXIcon = withAppWeight(FileXGlyph, 'FileXIcon');
export const FileXlsIcon = withAppWeight(FileXlsGlyph, 'FileXlsIcon');
export const FileZipIcon = withAppWeight(FileZipGlyph, 'FileZipIcon');
export const FilesIcon = withAppWeight(FilesGlyph, 'FilesIcon');
export const FingerprintIcon = withAppWeight(FingerprintGlyph, 'FingerprintIcon');
export const FlaskIcon = withAppWeight(FlaskGlyph, 'FlaskIcon');
export const FloppyDiskIcon = withAppWeight(FloppyDiskGlyph, 'FloppyDiskIcon');
export const FolderIcon = withAppWeight(FolderGlyph, 'FolderIcon');
export const FolderOpenIcon = withAppWeight(FolderOpenGlyph, 'FolderOpenIcon');
export const FolderPlusIcon = withAppWeight(FolderPlusGlyph, 'FolderPlusIcon');
// Stacked-folders glyph drawn by hand; Phosphor's Folders is a different shape.
export { KortixFoldersIcon as FoldersIcon } from './folders';
export const FunnelIcon = withAppWeight(FunnelGlyph, 'FunnelIcon');
export const GearSixIcon = withAppWeight(GearSixGlyph, 'GearSixIcon');
export const GitBranchIcon = withAppWeight(GitBranchGlyph, 'GitBranchIcon');
export const GitCommitIcon = withAppWeight(GitCommitGlyph, 'GitCommitIcon');
export const GitDiffIcon = withAppWeight(GitDiffGlyph, 'GitDiffIcon');
export const GitPullRequestIcon = withAppWeight(GitPullRequestGlyph, 'GitPullRequestIcon');
export const GithubLogoIcon = withAppWeight(GithubLogoGlyph, 'GithubLogoIcon');
export const GlobeIcon = withAppWeight(GlobeGlyph, 'GlobeIcon');
export const HammerIcon = withAppWeight(HammerGlyph, 'HammerIcon');
export const HardDrivesIcon = withAppWeight(HardDrivesGlyph, 'HardDrivesIcon');
export const HashIcon = withAppWeight(HashGlyph, 'HashIcon');
export const HeadphonesIcon = withAppWeight(HeadphonesGlyph, 'HeadphonesIcon');
export const HeartIcon = withAppWeight(HeartGlyph, 'HeartIcon');
export const HouseIcon = withAppWeight(HouseGlyph, 'HouseIcon');
export const ImageIcon = withAppWeight(ImageGlyph, 'ImageIcon');
export const InfinityIcon = withAppWeight(InfinityGlyph, 'InfinityIcon');
export const InfoIcon = withAppWeight(InfoGlyph, 'InfoIcon');
export const KanbanIcon = withAppWeight(KanbanGlyph, 'KanbanIcon');
export const KeyIcon = withAppWeight(KeyGlyph, 'KeyIcon');
export const LifebuoyIcon = withAppWeight(LifebuoyGlyph, 'LifebuoyIcon');
export const LightbulbIcon = withAppWeight(LightbulbGlyph, 'LightbulbIcon');
export const LightningIcon = withAppWeight(LightningGlyph, 'LightningIcon');
export const LinkBreakIcon = withAppWeight(LinkBreakGlyph, 'LinkBreakIcon');
export const LinkSimpleIcon = withAppWeight(LinkSimpleGlyph, 'LinkSimpleIcon');
export const ListChecksIcon = withAppWeight(ListChecksGlyph, 'ListChecksIcon');
export const ListIcon = withAppWeight(ListGlyph, 'ListIcon');
export const LockIcon = withAppWeight(LockGlyph, 'LockIcon');
export const LockOpenIcon = withAppWeight(LockOpenGlyph, 'LockOpenIcon');
export const MagnifyingGlassIcon = withAppWeight(MagnifyingGlassGlyph, 'MagnifyingGlassIcon');
export const MinusIcon = withAppWeight(MinusGlyph, 'MinusIcon');
export const MonitorIcon = withAppWeight(MonitorGlyph, 'MonitorIcon');
export const MonitorPlayIcon = withAppWeight(MonitorPlayGlyph, 'MonitorPlayIcon');
export const MoonIcon = withAppWeight(MoonGlyph, 'MoonIcon');
export const MusicNotesIcon = withAppWeight(MusicNotesGlyph, 'MusicNotesIcon');
export const NavigationArrowIcon = withAppWeight(NavigationArrowGlyph, 'NavigationArrowIcon');
export const NetworkIcon = withAppWeight(NetworkGlyph, 'NetworkIcon');
export const NotePencilIcon = withAppWeight(NotePencilGlyph, 'NotePencilIcon');
export const PaletteIcon = withAppWeight(PaletteGlyph, 'PaletteIcon');
export const PaperPlaneTiltIcon = withAppWeight(PaperPlaneTiltGlyph, 'PaperPlaneTiltIcon');
export const PaperclipIcon = withAppWeight(PaperclipGlyph, 'PaperclipIcon');
export const PauseIcon = withAppWeight(PauseGlyph, 'PauseIcon');
export const PencilIcon = withAppWeight(PencilGlyph, 'PencilIcon');
export const PencilSimpleIcon = withAppWeight(PencilSimpleGlyph, 'PencilSimpleIcon');
// Web's message edit button draws PencilSimple at regular weight (user-message.tsx).
export const PencilSimpleRegularIcon = withFixedWeight(PencilSimpleGlyph, 'regular', 'PencilSimpleRegularIcon');
export const PhoneIcon = withAppWeight(PhoneGlyph, 'PhoneIcon');
export const PhoneSlashIcon = withAppWeight(PhoneSlashGlyph, 'PhoneSlashIcon');
export const PlayIcon = withAppWeight(PlayGlyph, 'PlayIcon');
export const PlugIcon = withAppWeight(PlugGlyph, 'PlugIcon');
export const PlusIcon = withAppWeight(PlusGlyph, 'PlusIcon');
export const PresentationIcon = withAppWeight(PresentationGlyph, 'PresentationIcon');
export const ProhibitIcon = withAppWeight(ProhibitGlyph, 'ProhibitIcon');
export const PulseIcon = withAppWeight(PulseGlyph, 'PulseIcon');
export const QuestionIcon = withAppWeight(QuestionGlyph, 'QuestionIcon');
export const RadioButtonIcon = withAppWeight(RadioButtonGlyph, 'RadioButtonIcon');
export const ReadCvLogoIcon = withAppWeight(ReadCvLogoGlyph, 'ReadCvLogoIcon');
export const RepeatIcon = withAppWeight(RepeatGlyph, 'RepeatIcon');
export const RobotIcon = withAppWeight(RobotGlyph, 'RobotIcon');
export const RocketIcon = withAppWeight(RocketGlyph, 'RocketIcon');
export const ScissorsIcon = withAppWeight(ScissorsGlyph, 'ScissorsIcon');
export const SealCheckIcon = withAppWeight(SealCheckGlyph, 'SealCheckIcon');
export const ShieldCheckIcon = withAppWeight(ShieldCheckGlyph, 'ShieldCheckIcon');
export const ShieldIcon = withAppWeight(ShieldGlyph, 'ShieldIcon');
export const ShieldWarningIcon = withAppWeight(ShieldWarningGlyph, 'ShieldWarningIcon');
export const SignOutIcon = withAppWeight(SignOutGlyph, 'SignOutIcon');
export const SlackLogoIcon = withAppWeight(SlackLogoGlyph, 'SlackLogoIcon');
export const SlidersHorizontalIcon = withAppWeight(SlidersHorizontalGlyph, 'SlidersHorizontalIcon');
export const SortAscendingIcon = withAppWeight(SortAscendingGlyph, 'SortAscendingIcon');
export const SparkleIcon = withAppWeight(SparkleGlyph, 'SparkleIcon');
export const SpeakerHighIcon = withAppWeight(SpeakerHighGlyph, 'SpeakerHighIcon');
export const SquareIcon = withAppWeight(SquareGlyph, 'SquareIcon');
export const SquaresFourIcon = withAppWeight(SquaresFourGlyph, 'SquaresFourIcon');
export const StackIcon = withAppWeight(StackGlyph, 'StackIcon');
export const StarIcon = withAppWeight(StarGlyph, 'StarIcon');
export const StopCircleIcon = withAppWeight(StopCircleGlyph, 'StopCircleIcon');
export const SunIcon = withAppWeight(SunGlyph, 'SunIcon');
export const TableIcon = withAppWeight(TableGlyph, 'TableIcon');
export const TagIcon = withAppWeight(TagGlyph, 'TagIcon');
export const TargetIcon = withAppWeight(TargetGlyph, 'TargetIcon');
export const TerminalIcon = withAppWeight(TerminalGlyph, 'TerminalIcon');
export const TerminalWindowIcon = withAppWeight(TerminalWindowGlyph, 'TerminalWindowIcon');
export const TextTIcon = withAppWeight(TextTGlyph, 'TextTIcon');
export const TimerIcon = withAppWeight(TimerGlyph, 'TimerIcon');
export const TrashIcon = withAppWeight(TrashGlyph, 'TrashIcon');
export const TreeStructureIcon = withAppWeight(TreeStructureGlyph, 'TreeStructureIcon');
export const UploadIcon = withAppWeight(UploadGlyph, 'UploadIcon');
export const UserIcon = withAppWeight(UserGlyph, 'UserIcon');
export const UserPlusIcon = withAppWeight(UserPlusGlyph, 'UserPlusIcon');
export const UsersIcon = withAppWeight(UsersGlyph, 'UsersIcon');
export const UsersThreeIcon = withAppWeight(UsersThreeGlyph, 'UsersThreeIcon');
export const VibrateIcon = withAppWeight(VibrateGlyph, 'VibrateIcon');
export const VideoIcon = withAppWeight(VideoGlyph, 'VideoIcon');
export const WalletIcon = withAppWeight(WalletGlyph, 'WalletIcon');
export const WarningCircleIcon = withAppWeight(WarningCircleGlyph, 'WarningCircleIcon');
export const WarningIcon = withAppWeight(WarningGlyph, 'WarningIcon');
export const WebhooksLogoIcon = withAppWeight(WebhooksLogoGlyph, 'WebhooksLogoIcon');
export const WifiHighIcon = withAppWeight(WifiHighGlyph, 'WifiHighIcon');
export const WifiSlashIcon = withAppWeight(WifiSlashGlyph, 'WifiSlashIcon');
export const WrenchIcon = withAppWeight(WrenchGlyph, 'WrenchIcon');
export const XCircleIcon = withAppWeight(XCircleGlyph, 'XCircleIcon');
export const XIcon = withAppWeight(XGlyph, 'XIcon');

export type { AppIcon, AppIconProps } from './bind';
export { DEFAULT_ICON_WEIGHT } from './icon-config';
