/**
 * File, search, shell, PTY, todo, question, show, and skill tool calls for the
 * session parity fixture.
 *
 * Story: an agent adds a Recharts revenue chart to `acme-dashboard`. It loads
 * a design skill, searches and reads the currency helpers, asks which library
 * to use, edits and patches the components, fails and then passes the build,
 * runs the dev server in a PTY, and shows the result.
 *
 * Shapes follow the renderers in apps/web `features/session/tool/tools/` and
 * their mobile ports in apps/mobile `components/session/tool/tools/` +
 * `lib/session/tools/files-*.ts` / `web-*.ts`. Parsers:
 * - `@kortix/sdk` `shellExitCode` (`<exit_code>` tag), `parseReadOutput`,
 *   `patchVerb`, `parseQuestionAnswersFromOutput`, `extractSkillContent`,
 *   `extractSkillFiles`, `skillDocumentPath`, `isShowPayloadEmpty`;
 * - apps/web `tool/shared/file-list.tsx` `parseFilePaths` / `parseGrepOutput`
 *   (mobile: `lib/session/tool-output-parsers.ts`);
 * - PTY and show outputs as `.kortix/opencode/plugins/pty.ts` and
 *   `.kortix/opencode/tools/show.ts` write them (`packages/starter`).
 *
 * Diffs and `additions`/`deletions` were computed with jsdiff
 * (`createTwoFilesPatch`, `diffLines`) from the before/after strings below.
 */

import type { FixtureToolGroup } from '../types';

export const FILES_SHELL_TOOL_GROUP: FixtureToolGroup = {
  key: 'files-shell',
  prompt: 'Add a revenue chart to the acme-dashboard home page next to the revenue card, use compact currency on the card, and make sure the build still passes. Start the dev server when it is done.',
  reasoning: 'The card already formats money through `formatCurrency` in `src/lib/format.ts`, so I will read that helper and find every call site before I change anything. The chart library is a product choice, so I will **ask** before building. After the patch I will run `bun run build` and the unit tests, then start `vite` in a PTY.',
  summary: 'The dashboard home now renders `RevenueChart` (Recharts) in place of `LegacyRevenueTable`, and `RevenueCard` shows compact currency plus a signed `formatPercent` change. The first `bun run build` failed with exit code 1 because `formatPercent` did not exist; after adding it, `bun run typecheck`, `bun test src/lib` (4 pass, 0 fail), and `bun run build` pass. Notes are in `docs/revenue-widget.md`, and the dev server PTY is stopped.',
  specs: [
    // ─── Skill + search ────────────────────────────────────────────────────────
    {
      renderer: 'skill-tool.tsx',
      tool: 'skill',
      input: {
        name: 'frontend-design',
      },
      output: [
        '<skill_content name="frontend-design">',
        '# Skill: frontend-design',
        '',
        '---',
        'name: frontend-design',
        'description: Build production UI that matches the project design tokens.',
        '---',
        '',
        '## Rules',
        '',
        '1. Read `src/styles/tokens.css` before choosing a color, radius, or spacing value.',
        '2. Compose existing components from `src/components` before adding new ones.',
        '3. Charts use `var(--chart-1)` through `var(--chart-5)`; never hard-code a hex value.',
        '4. Every interactive element has a visible focus state.',
        '',
        '## Checklist',
        '',
        '- [ ] Light and dark theme',
        '- [ ] 360 px viewport without horizontal scroll',
        '- [ ] Loading, empty, and error states',
        '',
        'Base directory: /workspace/.kortix/opencode/skills/frontend-design',
        'Note: file paths in this skill are relative to the base directory.',
        '',
        '<skill_files>',
        '<file>/workspace/.kortix/opencode/skills/frontend-design/SKILL.md</file>',
        '<file>/workspace/.kortix/opencode/skills/frontend-design/references/tokens.md</file>',
        '<file>/workspace/.kortix/opencode/skills/frontend-design/scripts/audit-colors.sh</file>',
        '</skill_files>',
        '</skill_content>',
      ].join('\n'),
      title: 'Loaded skill: frontend-design',
      metadata: {
        name: 'frontend-design',
        dir: '/workspace/.kortix/opencode/skills/frontend-design',
      },
      error: 'Skill "frontend-design" not found. Available skills: kortix-design-system, testing, worktree',
      durationMs: 180,
      note: 'Output carries `<skill_content name>`, a `Base directory:` line (`extractSkillBaseDir` / `skillDocumentPath` resolve `SKILL.md` from it; the renderer strips it and the `Note:` line from the markdown), and `<skill_files>` with `<file>` rows (`extractSkillFiles`). Web and mobile share the SDK parsers; no field divergence.',
    },
    {
      renderer: 'glob-tool.tsx',
      tool: 'glob',
      input: {
        pattern: 'src/**/*.tsx',
        path: '/workspace/acme-dashboard',
      },
      output: [
        '/workspace/acme-dashboard/src/App.tsx',
        '/workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx',
        '/workspace/acme-dashboard/src/components/RevenueCard.tsx',
        '/workspace/acme-dashboard/src/components/Sidebar.tsx',
        '/workspace/acme-dashboard/src/main.tsx',
        '/workspace/acme-dashboard/src/pages/Dashboard.tsx',
        '/workspace/acme-dashboard/src/pages/Settings.tsx',
      ].join('\n'),
      title: 'acme-dashboard',
      metadata: {
        count: 7,
        truncated: false,
      },
      error: 'ENOENT: no such file or directory, scandir \'/workspace/acme-dashboard/source\'',
      durationMs: 95,
      note: 'One absolute path per line. `parseFilePaths` needs ≥70% of lines to start with `/`, `./`, or `~`. `src/**/*.tsx` is not a catch-all glob, so both surfaces label the row with the pattern and badge `7 files`.',
    },
    {
      renderer: 'grep-tool.tsx',
      tool: 'grep',
      input: {
        pattern: 'formatCurrency',
        path: '/workspace/acme-dashboard/src',
        include: '*.{ts,tsx}',
      },
      output: [
        'Found 5 matches',
        '',
        '/workspace/acme-dashboard/src/lib/format.ts:',
        '  Line 23: export function formatCurrency(value: number, options: FormatCurrencyOptions = {}): string {',
        '',
        '/workspace/acme-dashboard/src/components/RevenueCard.tsx:',
        '  Line 1: import { formatCurrency } from \'../lib/format\';',
        '  Line 15:       <span className="value">{formatCurrency(total)}</span>',
        '',
        '/workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx:',
        '  Line 1: import { formatCurrency } from \'../lib/format\';',
        '  Line 10:             <td>{formatCurrency(row.revenue)}</td>',
      ].join('\n'),
      title: 'formatCurrency',
      metadata: {
        matches: 5,
        truncated: false,
      },
      error: 'ripgrep failed: regex parse error: unclosed group',
      durationMs: 140,
      note: '`Found N matches` header, then blank-line-separated blocks of `/abs/path:` + `  Line N: text` (`parseGrepOutput`). The blank line after the header is deliberate: `parseGrepOutput` matches `^Found\\s+(\\d+)\\s+match` and slices it off, leaving `es` glued to the first file line, so without the blank line the first file group is dropped on web AND mobile (same parser). Both surfaces take the row subtitle from `getDirectory(input.path)`, which names the PARENT of the searched directory (`/workspace/acme-dashboard`, not `…/src`).',
    },
    {
      renderer: 'read-tool.tsx',
      tool: 'read',
      input: {
        filePath: '/workspace/acme-dashboard/src/lib/format.ts',
      },
      output: [
        '<path>/workspace/acme-dashboard/src/lib/format.ts</path>',
        '<type>file</type>',
        '<content>',
        '1: const formatters = new Map<string, Intl.NumberFormat>();',
        '2: ',
        '3: function getFormatter(currency: string, compact: boolean): Intl.NumberFormat {',
        '4:   const key = `${currency}:${compact ? \'compact\' : \'standard\'}`;',
        '5:   let formatter = formatters.get(key);',
        '6:   if (!formatter) {',
        '7:     formatter = new Intl.NumberFormat(\'en-US\', {',
        '8:       style: \'currency\',',
        '9:       currency,',
        '10:       notation: compact ? \'compact\' : \'standard\',',
        '11:       maximumFractionDigits: compact ? 1 : 2,',
        '12:     });',
        '13:     formatters.set(key, formatter);',
        '14:   }',
        '15:   return formatter;',
        '16: }',
        '17: ',
        '18: export interface FormatCurrencyOptions {',
        '19:   currency?: string;',
        '20:   compact?: boolean;',
        '21: }',
        '22: ',
        '23: export function formatCurrency(value: number, options: FormatCurrencyOptions = {}): string {',
        '24:   return getFormatter(options.currency ?? \'USD\', options.compact ?? false).format(value);',
        '25: }',
        '',
        '(End of file - total 25 lines)',
        '</content>',
      ].join('\n'),
      title: 'src/lib/format.ts',
      metadata: {
        preview: [
          'const formatters = new Map<string, Intl.NumberFormat>();',
          '',
          'function getFormatter(currency: string, compact: boolean): Intl.NumberFormat {',
          '  const key = `${currency}:${compact ? \'compact\' : \'standard\'}`;',
          '  let formatter = formatters.get(key);',
          '  if (!formatter) {',
          '    formatter = new Intl.NumberFormat(\'en-US\', {',
          '      style: \'currency\',',
          '      currency,',
          '      notation: compact ? \'compact\' : \'standard\',',
          '      maximumFractionDigits: compact ? 1 : 2,',
          '    });',
          '    formatters.set(key, formatter);',
          '  }',
          '  return formatter;',
          '}',
          '',
          'export interface FormatCurrencyOptions {',
          '  currency?: string;',
          '  compact?: boolean;',
        ].join('\n'),
        truncated: false,
        loaded: ['/workspace/acme-dashboard/src/AGENTS.md'],
      },
      error: [
        'File not found: /workspace/acme-dashboard/src/lib/formatters.ts',
        '',
        'Did you mean one of these?',
        '/workspace/acme-dashboard/src/lib/format.ts',
      ].join('\n'),
      durationMs: 60,
      note: '`<path>` + `<type>` + `<content>` with `N: ` line prefixes, as the OpenCode read tool returns them; `parseReadOutput` strips the prefixes. The `(End of file - total N lines)` footer sits inside `<content>`, so both surfaces render it as the last code line. `metadata.loaded` draws the `+ src/AGENTS.md` row under the call on the inline surface only (both apps).',
    },
    {
      renderer: 'list-tool.tsx',
      tool: 'list',
      input: {
        path: '/workspace/acme-dashboard/src/components',
      },
      output: [
        '/workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx',
        '/workspace/acme-dashboard/src/components/RevenueCard.tsx',
        '/workspace/acme-dashboard/src/components/Sidebar.tsx',
        '/workspace/acme-dashboard/src/components/Sidebar.module.css',
      ].join('\n'),
      title: 'src/components',
      metadata: {
        count: 4,
        truncated: false,
      },
      error: 'ENOENT: no such file or directory, scandir \'/workspace/acme-dashboard/src/widgets\'',
      durationMs: 45,
      note: 'Flat absolute paths, because `parseFilePaths` is the only body parser on both surfaces. The OpenCode `list` tool itself prints an indented tree (`/dir/` then `  name` rows); that shape fails the 70% path-line rule and falls to `ToolOutputFallback` on web and mobile. Subtitle is `getDirectory(input.path)` (the parent directory) on both.',
    },
    // ─── Decide ────────────────────────────────────────────────────────────────
    {
      renderer: 'question-tool.tsx',
      tool: 'question',
      input: {
        questions: [
          {
            question: 'Which chart library should the revenue widget use?',
            header: 'Chart library',
            options: [
              {
                label: 'Recharts',
                description: 'Already in package.json; composable SVG charts',
              },
              {
                label: 'Chart.js',
                description: 'Canvas rendering; needs the react-chartjs-2 wrapper',
              },
              {
                label: 'visx',
                description: 'Low-level primitives; the most code to write',
              },
            ],
          },
          {
            question: 'Which extras should ship with the first version?',
            header: 'Extras',
            multiple: true,
            options: [
              {
                label: 'CSV export',
                description: 'Download the visible range as a CSV file',
              },
              {
                label: 'Date range filter',
                description: '7d / 30d / 90d presets above the chart',
              },
              {
                label: 'Compare to last period',
                description: 'Dashed overlay series for the previous range',
              },
            ],
          },
        ],
      },
      output: 'User has answered your questions: "Which chart library should the revenue widget use?"="Recharts", "Which extras should ship with the first version?"="CSV export, Date range filter". You can now continue with the user\'s answers in mind.',
      title: 'Asked 2 questions',
      metadata: {
        answers: [['Recharts'], ['CSV export', 'Date range filter']],
      },
      error: 'The user dismissed this question',
      durationMs: 48000,
      note: 'Answered call. Both surfaces read `metadata.answers` (string[][]) first and fall back to the `"q"="a"` pairs in the output (`parseQuestionAnswersFromOutput`, which yields one joined string per question). The running state doubles as the unanswered case: `input.questions` is a full QuestionInfo list, question 2 is `multiple`. Question text carries no `"`, so the output pair regex stays valid.',
    },
    {
      renderer: 'todo-write-tool.tsx',
      tool: 'todowrite',
      input: {
        todos: [
          {
            id: '1',
            content: 'Read the currency helpers in src/lib/format.ts',
            status: 'completed',
            priority: 'high',
          },
          {
            id: '2',
            content: 'Ask which chart library and extras to ship',
            status: 'completed',
            priority: 'high',
          },
          {
            id: '3',
            content: 'Build RevenueChart and wire it into the dashboard',
            status: 'in_progress',
            priority: 'high',
          },
          {
            id: '4',
            content: 'Run typecheck, unit tests, and a production build',
            status: 'pending',
            priority: 'medium',
          },
          {
            id: '5',
            content: 'Port LegacyRevenueTable sorting to the chart',
            status: 'cancelled',
            priority: 'low',
          },
        ],
      },
      output: [
        '[',
        '  {',
        '    "id": "1",',
        '    "content": "Read the currency helpers in src/lib/format.ts",',
        '    "status": "completed",',
        '    "priority": "high"',
        '  },',
        '  {',
        '    "id": "2",',
        '    "content": "Ask which chart library and extras to ship",',
        '    "status": "completed",',
        '    "priority": "high"',
        '  },',
        '  {',
        '    "id": "3",',
        '    "content": "Build RevenueChart and wire it into the dashboard",',
        '    "status": "in_progress",',
        '    "priority": "high"',
        '  },',
        '  {',
        '    "id": "4",',
        '    "content": "Run typecheck, unit tests, and a production build",',
        '    "status": "pending",',
        '    "priority": "medium"',
        '  },',
        '  {',
        '    "id": "5",',
        '    "content": "Port LegacyRevenueTable sorting to the chart",',
        '    "status": "cancelled",',
        '    "priority": "low"',
        '  }',
        ']',
      ].join('\n'),
      title: '3 todos',
      metadata: {
        todos: [
          {
            id: '1',
            content: 'Read the currency helpers in src/lib/format.ts',
            status: 'completed',
            priority: 'high',
          },
          {
            id: '2',
            content: 'Ask which chart library and extras to ship',
            status: 'completed',
            priority: 'high',
          },
          {
            id: '3',
            content: 'Build RevenueChart and wire it into the dashboard',
            status: 'in_progress',
            priority: 'high',
          },
          {
            id: '4',
            content: 'Run typecheck, unit tests, and a production build',
            status: 'pending',
            priority: 'medium',
          },
          {
            id: '5',
            content: 'Port LegacyRevenueTable sorting to the chart',
            status: 'cancelled',
            priority: 'low',
          },
        ],
      },
      error: 'Invalid input: todos[2].status must be one of "pending", "in_progress", "completed", "cancelled"',
      durationMs: 30,
      note: 'Five todos, all four statuses. Both surfaces read `input.todos`, then `metadata.todos`, then the streaming input (`parseTodos`); the output JSON is not read. Title counts todos whose status is not `completed`, as OpenCode writes it.',
    },
    // ─── Edit ──────────────────────────────────────────────────────────────────
    {
      renderer: 'edit-tool.tsx',
      tool: 'edit',
      input: {
        filePath: '/workspace/acme-dashboard/src/components/RevenueCard.tsx',
        oldString: [
          '      <span className="value">{formatCurrency(total)}</span>',
          '      <span className={delta >= 0 ? \'delta up\' : \'delta down\'}>',
          '        {(delta * 100).toFixed(1)}%',
        ].join('\n'),
        newString: [
          '      <span className="value">{formatCurrency(total, { compact: true })}</span>',
          '      <span className={delta >= 0 ? \'delta up\' : \'delta down\'}>',
          '        {formatPercent(delta)}',
        ].join('\n'),
      },
      output: 'Edit applied successfully.',
      title: 'src/components/RevenueCard.tsx',
      metadata: {
        diagnostics: {},
        diff: [
          'Index: /workspace/acme-dashboard/src/components/RevenueCard.tsx',
          '===================================================================',
          '--- /workspace/acme-dashboard/src/components/RevenueCard.tsx\t',
          '+++ /workspace/acme-dashboard/src/components/RevenueCard.tsx\t',
          '@@ -1,4 +1,4 @@',
          '-import { formatCurrency } from \'../lib/format\';',
          '+import { formatCurrency, formatPercent } from \'../lib/format\';',
          ' ',
          ' interface RevenueCardProps {',
          '   label: string;',
          '@@ -12,9 +12,9 @@',
          '   return (',
          '     <section className="card">',
          '       <h3 className="card-label">{label}</h3>',
          '-      <span className="value">{formatCurrency(total)}</span>',
          '+      <span className="value">{formatCurrency(total, { compact: true })}</span>',
          '       <span className={delta >= 0 ? \'delta up\' : \'delta down\'}>',
          '-        {(delta * 100).toFixed(1)}%',
          '+        {formatPercent(delta)}',
          '       </span>',
          '     </section>',
          '   );',
        ].join('\n'),
        filediff: {
          file: '/workspace/acme-dashboard/src/components/RevenueCard.tsx',
          before: [
            'import { formatCurrency } from \'../lib/format\';',
            '',
            'interface RevenueCardProps {',
            '  label: string;',
            '  total: number;',
            '  previous: number;',
            '}',
            '',
            'export function RevenueCard({ label, total, previous }: RevenueCardProps) {',
            '  const delta = previous === 0 ? 0 : (total - previous) / previous;',
            '',
            '  return (',
            '    <section className="card">',
            '      <h3 className="card-label">{label}</h3>',
            '      <span className="value">{formatCurrency(total)}</span>',
            '      <span className={delta >= 0 ? \'delta up\' : \'delta down\'}>',
            '        {(delta * 100).toFixed(1)}%',
            '      </span>',
            '    </section>',
            '  );',
            '}',
            '',
          ].join('\n'),
          after: [
            'import { formatCurrency, formatPercent } from \'../lib/format\';',
            '',
            'interface RevenueCardProps {',
            '  label: string;',
            '  total: number;',
            '  previous: number;',
            '}',
            '',
            'export function RevenueCard({ label, total, previous }: RevenueCardProps) {',
            '  const delta = previous === 0 ? 0 : (total - previous) / previous;',
            '',
            '  return (',
            '    <section className="card">',
            '      <h3 className="card-label">{label}</h3>',
            '      <span className="value">{formatCurrency(total, { compact: true })}</span>',
            '      <span className={delta >= 0 ? \'delta up\' : \'delta down\'}>',
            '        {formatPercent(delta)}',
            '      </span>',
            '    </section>',
            '  );',
            '}',
            '',
          ].join('\n'),
          additions: 3,
          deletions: 3,
        },
      },
      error: 'oldString not found in content',
      durationMs: 420,
      note: 'Both surfaces diff `metadata.filediff.before/after` (whole file) and fall back to `input.oldString/newString` when `filediff` is absent, so pending/running states still draw a diff from the input. `metadata.diff` (unified) is not read by either renderer; it is kept because the runtime sends it. The import change lives only in the filediff, not in the input strings.',
    },
    {
      renderer: 'apply-patch-tool.tsx',
      tool: 'apply_patch',
      input: {
        patchText: [
          '*** Begin Patch',
          '*** Add File: src/components/RevenueChart.tsx',
          '+import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from \'recharts\';',
          '+import { formatCurrency } from \'../lib/format\';',
          '+',
          '+export interface RevenuePoint {',
          '+  day: string;',
          '+  revenue: number;',
          '+}',
          '+',
          '+export function RevenueChart({ data }: { data: RevenuePoint[] }) {',
          '+  return (',
          '+    <ResponsiveContainer width="100%" height={240}>',
          '+      <AreaChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>',
          '+        <XAxis dataKey="day" tickLine={false} axisLine={false} />',
          '+        <YAxis tickFormatter={(v: number) => formatCurrency(v, { compact: true })} width={56} />',
          '+        <Tooltip formatter={(v: number) => formatCurrency(v)} />',
          '+        <Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.12} />',
          '+      </AreaChart>',
          '+    </ResponsiveContainer>',
          '+  );',
          '+}',
          '*** Update File: src/pages/Dashboard.tsx',
          '@@',
          '-import { LegacyRevenueTable } from \'../components/LegacyRevenueTable\';',
          ' import { RevenueCard } from \'../components/RevenueCard\';',
          '+import { RevenueChart } from \'../components/RevenueChart\';',
          ' import { useRevenue } from \'../hooks/useRevenue\';',
          '@@',
          '       <RevenueCard label="Revenue (30d)" total={totals.current} previous={totals.previous} />',
          '-      <LegacyRevenueTable rows={series} />',
          '+      <RevenueChart data={series} />',
          '     </main>',
          '*** Delete File: src/components/LegacyRevenueTable.tsx',
          '*** End Patch',
        ].join('\n'),
      },
      output: [
        'Success. Updated the following files:',
        'A src/components/RevenueChart.tsx',
        'M src/pages/Dashboard.tsx',
        'D src/components/LegacyRevenueTable.tsx',
      ].join('\n'),
      metadata: {
        diff: [
          'Index: /workspace/acme-dashboard/src/components/RevenueChart.tsx',
          '===================================================================',
          '--- /workspace/acme-dashboard/src/components/RevenueChart.tsx\t',
          '+++ /workspace/acme-dashboard/src/components/RevenueChart.tsx\t',
          '@@ -0,0 +1,20 @@',
          '+import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from \'recharts\';',
          '+import { formatCurrency } from \'../lib/format\';',
          '+',
          '+export interface RevenuePoint {',
          '+  day: string;',
          '+  revenue: number;',
          '+}',
          '+',
          '+export function RevenueChart({ data }: { data: RevenuePoint[] }) {',
          '+  return (',
          '+    <ResponsiveContainer width="100%" height={240}>',
          '+      <AreaChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>',
          '+        <XAxis dataKey="day" tickLine={false} axisLine={false} />',
          '+        <YAxis tickFormatter={(v: number) => formatCurrency(v, { compact: true })} width={56} />',
          '+        <Tooltip formatter={(v: number) => formatCurrency(v)} />',
          '+        <Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.12} />',
          '+      </AreaChart>',
          '+    </ResponsiveContainer>',
          '+  );',
          '+}',
          'Index: /workspace/acme-dashboard/src/pages/Dashboard.tsx',
          '===================================================================',
          '--- /workspace/acme-dashboard/src/pages/Dashboard.tsx\t',
          '+++ /workspace/acme-dashboard/src/pages/Dashboard.tsx\t',
          '@@ -1,5 +1,5 @@',
          '-import { LegacyRevenueTable } from \'../components/LegacyRevenueTable\';',
          ' import { RevenueCard } from \'../components/RevenueCard\';',
          '+import { RevenueChart } from \'../components/RevenueChart\';',
          ' import { useRevenue } from \'../hooks/useRevenue\';',
          ' ',
          ' export function Dashboard() {',
          '@@ -8,7 +8,7 @@',
          '   return (',
          '     <main className="dashboard">',
          '       <RevenueCard label="Revenue (30d)" total={totals.current} previous={totals.previous} />',
          '-      <LegacyRevenueTable rows={series} />',
          '+      <RevenueChart data={series} />',
          '     </main>',
          '   );',
          ' }',
          'Index: /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx',
          '===================================================================',
          '--- /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx\t',
          '+++ /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx\t',
          '@@ -1,16 +0,0 @@',
          '-import { formatCurrency } from \'../lib/format\';',
          '-',
          '-export function LegacyRevenueTable({ rows }: { rows: { day: string; revenue: number }[] }) {',
          '-  return (',
          '-    <table className="legacy-table">',
          '-      <tbody>',
          '-        {rows.map((row) => (',
          '-          <tr key={row.day}>',
          '-            <td>{row.day}</td>',
          '-            <td>{formatCurrency(row.revenue)}</td>',
          '-          </tr>',
          '-        ))}',
          '-      </tbody>',
          '-    </table>',
          '-  );',
          '-}',
        ].join('\n'),
        files: [
          {
            filePath: '/workspace/acme-dashboard/src/components/RevenueChart.tsx',
            relativePath: 'src/components/RevenueChart.tsx',
            type: 'add',
            diff: [
              'Index: /workspace/acme-dashboard/src/components/RevenueChart.tsx',
              '===================================================================',
              '--- /workspace/acme-dashboard/src/components/RevenueChart.tsx\t',
              '+++ /workspace/acme-dashboard/src/components/RevenueChart.tsx\t',
              '@@ -0,0 +1,20 @@',
              '+import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from \'recharts\';',
              '+import { formatCurrency } from \'../lib/format\';',
              '+',
              '+export interface RevenuePoint {',
              '+  day: string;',
              '+  revenue: number;',
              '+}',
              '+',
              '+export function RevenueChart({ data }: { data: RevenuePoint[] }) {',
              '+  return (',
              '+    <ResponsiveContainer width="100%" height={240}>',
              '+      <AreaChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>',
              '+        <XAxis dataKey="day" tickLine={false} axisLine={false} />',
              '+        <YAxis tickFormatter={(v: number) => formatCurrency(v, { compact: true })} width={56} />',
              '+        <Tooltip formatter={(v: number) => formatCurrency(v)} />',
              '+        <Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.12} />',
              '+      </AreaChart>',
              '+    </ResponsiveContainer>',
              '+  );',
              '+}',
            ].join('\n'),
            before: '',
            after: [
              'import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from \'recharts\';',
              'import { formatCurrency } from \'../lib/format\';',
              '',
              'export interface RevenuePoint {',
              '  day: string;',
              '  revenue: number;',
              '}',
              '',
              'export function RevenueChart({ data }: { data: RevenuePoint[] }) {',
              '  return (',
              '    <ResponsiveContainer width="100%" height={240}>',
              '      <AreaChart data={data} margin={{ top: 8, right: 8, bottom: 0, left: 0 }}>',
              '        <XAxis dataKey="day" tickLine={false} axisLine={false} />',
              '        <YAxis tickFormatter={(v: number) => formatCurrency(v, { compact: true })} width={56} />',
              '        <Tooltip formatter={(v: number) => formatCurrency(v)} />',
              '        <Area type="monotone" dataKey="revenue" stroke="var(--chart-1)" fill="var(--chart-1)" fillOpacity={0.12} />',
              '      </AreaChart>',
              '    </ResponsiveContainer>',
              '  );',
              '}',
              '',
            ].join('\n'),
            additions: 20,
            deletions: 0,
          },
          {
            filePath: '/workspace/acme-dashboard/src/pages/Dashboard.tsx',
            relativePath: 'src/pages/Dashboard.tsx',
            type: 'update',
            diff: [
              'Index: /workspace/acme-dashboard/src/pages/Dashboard.tsx',
              '===================================================================',
              '--- /workspace/acme-dashboard/src/pages/Dashboard.tsx\t',
              '+++ /workspace/acme-dashboard/src/pages/Dashboard.tsx\t',
              '@@ -1,5 +1,5 @@',
              '-import { LegacyRevenueTable } from \'../components/LegacyRevenueTable\';',
              ' import { RevenueCard } from \'../components/RevenueCard\';',
              '+import { RevenueChart } from \'../components/RevenueChart\';',
              ' import { useRevenue } from \'../hooks/useRevenue\';',
              ' ',
              ' export function Dashboard() {',
              '@@ -8,7 +8,7 @@',
              '   return (',
              '     <main className="dashboard">',
              '       <RevenueCard label="Revenue (30d)" total={totals.current} previous={totals.previous} />',
              '-      <LegacyRevenueTable rows={series} />',
              '+      <RevenueChart data={series} />',
              '     </main>',
              '   );',
              ' }',
            ].join('\n'),
            before: [
              'import { LegacyRevenueTable } from \'../components/LegacyRevenueTable\';',
              'import { RevenueCard } from \'../components/RevenueCard\';',
              'import { useRevenue } from \'../hooks/useRevenue\';',
              '',
              'export function Dashboard() {',
              '  const { totals, series } = useRevenue(\'30d\');',
              '',
              '  return (',
              '    <main className="dashboard">',
              '      <RevenueCard label="Revenue (30d)" total={totals.current} previous={totals.previous} />',
              '      <LegacyRevenueTable rows={series} />',
              '    </main>',
              '  );',
              '}',
              '',
            ].join('\n'),
            after: [
              'import { RevenueCard } from \'../components/RevenueCard\';',
              'import { RevenueChart } from \'../components/RevenueChart\';',
              'import { useRevenue } from \'../hooks/useRevenue\';',
              '',
              'export function Dashboard() {',
              '  const { totals, series } = useRevenue(\'30d\');',
              '',
              '  return (',
              '    <main className="dashboard">',
              '      <RevenueCard label="Revenue (30d)" total={totals.current} previous={totals.previous} />',
              '      <RevenueChart data={series} />',
              '    </main>',
              '  );',
              '}',
              '',
            ].join('\n'),
            additions: 2,
            deletions: 2,
          },
          {
            filePath: '/workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx',
            relativePath: 'src/components/LegacyRevenueTable.tsx',
            type: 'delete',
            diff: [
              'Index: /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx',
              '===================================================================',
              '--- /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx\t',
              '+++ /workspace/acme-dashboard/src/components/LegacyRevenueTable.tsx\t',
              '@@ -1,16 +0,0 @@',
              '-import { formatCurrency } from \'../lib/format\';',
              '-',
              '-export function LegacyRevenueTable({ rows }: { rows: { day: string; revenue: number }[] }) {',
              '-  return (',
              '-    <table className="legacy-table">',
              '-      <tbody>',
              '-        {rows.map((row) => (',
              '-          <tr key={row.day}>',
              '-            <td>{row.day}</td>',
              '-            <td>{formatCurrency(row.revenue)}</td>',
              '-          </tr>',
              '-        ))}',
              '-      </tbody>',
              '-    </table>',
              '-  );',
              '-}',
            ].join('\n'),
            before: [
              'import { formatCurrency } from \'../lib/format\';',
              '',
              'export function LegacyRevenueTable({ rows }: { rows: { day: string; revenue: number }[] }) {',
              '  return (',
              '    <table className="legacy-table">',
              '      <tbody>',
              '        {rows.map((row) => (',
              '          <tr key={row.day}>',
              '            <td>{row.day}</td>',
              '            <td>{formatCurrency(row.revenue)}</td>',
              '          </tr>',
              '        ))}',
              '      </tbody>',
              '    </table>',
              '  );',
              '}',
              '',
            ].join('\n'),
            after: '',
            additions: 0,
            deletions: 16,
          },
        ],
        diagnostics: {},
      },
      error: [
        'apply_patch verification failed: Failed to find expected lines in /workspace/acme-dashboard/src/pages/Dashboard.tsx:',
        '      <LegacyRevenueTable rows={series} />',
      ].join('\n'),
      durationMs: 380,
      note: 'Three files (add / update / delete) in `metadata.files[]` with `filePath`, `relativePath`, `type`, `before`, `after`, `diff`, `additions`, `deletions`. Mixed ops → `patchVerb` says `Changed`, subtitle `3 files`. Each row opens an inline before/after diff (both sides non-null, including `""` for add/delete). Running state has no `files`, so both surfaces show the `Preparing changes…` shimmer. No field divergence.',
    },
    // ─── Verify ────────────────────────────────────────────────────────────────
    {
      renderer: 'bash-tool.tsx',
      tool: 'bash',
      input: {
        command: [
          'cd /workspace/acme-dashboard',
          'bun run build',
        ].join('\n'),
        description: 'Build the dashboard for production',
        timeout: 120000,
      },
      output: [
        '$ vite build',
        'vite v6.3.5 building for production...',
        'transforming...',
        '✓ 412 modules transformed.',
        'x Build failed in 1.84s',
        'error during build:',
        'src/components/RevenueCard.tsx (1:26): "formatPercent" is not exported by "src/lib/format.ts", imported by "src/components/RevenueCard.tsx".',
        'file: /workspace/acme-dashboard/src/components/RevenueCard.tsx:1:26',
        '',
        '1: import { formatCurrency, formatPercent } from \'../lib/format\';',
        '                            ^',
        'error: script "build" exited with code 1',
        '<exit_code>1</exit_code>',
      ].join('\n'),
      title: 'Build the dashboard for production',
      metadata: {
        output: [
          '$ vite build',
          'vite v6.3.5 building for production...',
          'transforming...',
          '✓ 412 modules transformed.',
          'x Build failed in 1.84s',
          'error during build:',
          'src/components/RevenueCard.tsx (1:26): "formatPercent" is not exported by "src/lib/format.ts", imported by "src/components/RevenueCard.tsx".',
          'file: /workspace/acme-dashboard/src/components/RevenueCard.tsx:1:26',
          '',
          '1: import { formatCurrency, formatPercent } from \'../lib/format\';',
          '                            ^',
          'error: script "build" exited with code 1',
        ].join('\n'),
        exit: 1,
        description: 'Build the dashboard for production',
        truncated: false,
      },
      runningTitle: 'Build the dashboard for production',
      runningMetadata: {
        output: [
          '$ vite build',
          'vite v6.3.5 building for production...',
          'transforming...',
        ].join('\n'),
        description: 'Build the dashboard for production',
      },
      error: 'Command timed out after 120000 ms',
      durationMs: 4200,
      note: 'Non-zero exit. Both surfaces read the exit code ONLY from the `<exit_code>N</exit_code>` tag in the completed output (`shellExitCode`); `metadata.exit` is ignored, so it is kept only as the runtime field. `partOutput` strips the tag before display. Running `metadata.output` is not drawn on either surface (partOutput is empty until completed).',
    },
    {
      renderer: 'edit-tool.tsx',
      tool: 'morph_edit',
      input: {
        target_filepath: '/workspace/acme-dashboard/src/lib/format.ts',
        instructions: 'I am adding a formatPercent helper below formatCurrency.',
        code_edit: [
          '// ... existing code ...',
          'export function formatCurrency(value: number, options: FormatCurrencyOptions = {}): string {',
          '  return getFormatter(options.currency ?? \'USD\', options.compact ?? false).format(value);',
          '}',
          '',
          'const percentFormatter = new Intl.NumberFormat(\'en-US\', {',
          '  style: \'percent\',',
          '  maximumFractionDigits: 1,',
          '  signDisplay: \'exceptZero\',',
          '});',
          '',
          'export function formatPercent(ratio: number): string {',
          '  return percentFormatter.format(ratio);',
          '}',
        ].join('\n'),
      },
      output: 'Applied edit to /workspace/acme-dashboard/src/lib/format.ts',
      title: 'src/lib/format.ts',
      metadata: {},
      error: 'Morph apply failed: the edit could not be merged into src/lib/format.ts',
      durationMs: 950,
      note: '`morph_edit` input differs from `edit`: `target_filepath`, `instructions`, `code_edit`. With no `metadata.filediff` and no `oldString/newString`, both surfaces take the Morph branch: italic instructions over a `ToolCodeCard` of `code_edit`. The filename comes from `streamingInput.target_filepath` on both.',
    },
    {
      renderer: 'bash-tool.tsx',
      tool: 'bash',
      input: {
        command: [
          'cd /workspace/acme-dashboard && \\',
          '  bun run typecheck && \\',
          '  bun test src/lib && \\',
          '  bun run build',
        ].join('\n'),
        description: 'typecheck, test, and build the dashboard',
      },
      output: [
        '$ tsc --noEmit',
        'bun test v1.2.19 (aad3abea)',
        '',
        'src/lib/format.test.ts:',
        '(pass) formatCurrency > formats USD with two decimals [0.41ms]',
        '(pass) formatCurrency > uses compact notation when asked [0.12ms]',
        '(pass) formatPercent > signs a positive ratio [0.08ms]',
        '(pass) formatPercent > keeps zero unsigned [0.03ms]',
        '',
        ' 4 pass',
        ' 0 fail',
        ' 6 expect() calls',
        'Ran 4 tests across 1 file. [38.00ms]',
        '$ vite build',
        'vite v6.3.5 building for production...',
        'transforming...',
        '✓ 415 modules transformed.',
        'rendering chunks...',
        'computing gzip size...',
        'dist/index.html                   0.46 kB │ gzip:   0.30 kB',
        'dist/assets/index-BqY3k1Zs.css    4.12 kB │ gzip:   1.38 kB',
        'dist/assets/index-C8f2mD9a.js   486.37 kB │ gzip: 151.64 kB',
        '✓ built in 3.21s',
        '<exit_code>0</exit_code>',
      ].join('\n'),
      title: 'typecheck, test, and build the dashboard',
      metadata: {
        output: [
          '$ tsc --noEmit',
          'bun test v1.2.19 (aad3abea)',
          '',
          'src/lib/format.test.ts:',
          '(pass) formatCurrency > formats USD with two decimals [0.41ms]',
          '(pass) formatCurrency > uses compact notation when asked [0.12ms]',
          '(pass) formatPercent > signs a positive ratio [0.08ms]',
          '(pass) formatPercent > keeps zero unsigned [0.03ms]',
          '',
          ' 4 pass',
          ' 0 fail',
          ' 6 expect() calls',
          'Ran 4 tests across 1 file. [38.00ms]',
          '$ vite build',
          'vite v6.3.5 building for production...',
          'transforming...',
          '✓ 415 modules transformed.',
          'rendering chunks...',
          'computing gzip size...',
          'dist/index.html                   0.46 kB │ gzip:   0.30 kB',
          'dist/assets/index-BqY3k1Zs.css    4.12 kB │ gzip:   1.38 kB',
          'dist/assets/index-C8f2mD9a.js   486.37 kB │ gzip: 151.64 kB',
          '✓ built in 3.21s',
        ].join('\n'),
        exit: 0,
        description: 'typecheck, test, and build the dashboard',
        truncated: false,
      },
      runningTitle: 'typecheck, test, and build the dashboard',
      runningMetadata: {
        output: [
          '$ tsc --noEmit',
          'bun test v1.2.19 (aad3abea)',
          '',
          'src/lib/format.test.ts:',
        ].join('\n'),
        description: 'typecheck, test, and build the dashboard',
      },
      error: 'Command aborted: the session was interrupted',
      durationMs: 2600,
      note: 'Exit 0 with a four-line command (the first line has no indent, so `dedentCommand` keeps the continuation indent; the trigger shows `+3`). The lower-case description exercises `bashRowTitle` sentence-casing on both surfaces. Output avoids `warning:` and `Traceback`, so it renders as plain output, not structured sections.',
    },
    {
      renderer: 'write-tool.tsx',
      tool: 'write',
      input: {
        filePath: '/workspace/acme-dashboard/docs/revenue-widget.md',
        content: [
          '# Revenue widget',
          '',
          'The dashboard home shows revenue for the selected range as a card and an area chart.',
          '',
          '## Components',
          '',
          '| Component | File | Purpose |',
          '| --- | --- | --- |',
          '| `RevenueCard` | `src/components/RevenueCard.tsx` | Total and change against the previous period |',
          '| `RevenueChart` | `src/components/RevenueChart.tsx` | Daily revenue as a Recharts area chart |',
          '',
          '## Formatting',
          '',
          '- `formatCurrency(value, { compact: true })` renders `$12.4K` on axes and cards.',
          '- `formatPercent(ratio)` renders a signed change such as `+8.3%`.',
          '',
          '## Next',
          '',
          '1. CSV export of the visible range.',
          '2. Date range presets: 7d, 30d, 90d.',
          '',
        ].join('\n'),
      },
      output: 'Wrote file successfully.',
      title: 'docs/revenue-widget.md',
      metadata: {
        diagnostics: {},
        filepath: '/workspace/acme-dashboard/docs/revenue-widget.md',
        exists: false,
      },
      error: 'EACCES: permission denied, open \'/workspace/acme-dashboard/docs/revenue-widget.md\'',
      durationMs: 70,
      note: 'Both surfaces render `input.content` in a `ToolCodeCard` (language `md`) and count its lines as the `+N` stat; output and metadata are not read.',
    },
    // ─── Dev server (one PTY id) ───────────────────────────────────────────────
    {
      renderer: 'pty-spawn-tool.tsx',
      tool: 'pty_spawn',
      input: {
        command: 'bun',
        args: ['run', 'dev'],
        workdir: '/workspace/acme-dashboard',
        title: 'Dev server',
        description: 'Start the Vite dev server',
      },
      output: [
        '<kortix_system type="pty-spawn" source="opencode-pty">',
        '<pty_spawned>',
        'ID: pty_5c0e9a41',
        'Title: Dev server',
        'Command: bun run dev',
        'Workdir: /workspace/acme-dashboard',
        'PID: 4821',
        'Status: running',
        '</pty_spawned>',
        '</kortix_system>',
      ].join('\n'),
      title: 'Dev server',
      metadata: {},
      error: 'Tool execution aborted',
      durationMs: 310,
      note: 'Output exactly as `.kortix/opencode/plugins/pty.ts` writes it: `<kortix_system>` wrapper around `<pty_spawned>` `Key: value` lines. `input.command` is the executable only (`bun`); the parsed `Command:` line wins on both surfaces. Pending/running states show `input.title` as the subtitle.',
    },
    {
      renderer: 'pty-write-tool.tsx',
      tool: 'pty_write',
      input: {
        id: 'pty_5c0e9a41',
        data: [
          'r',
          '',
        ].join('\n'),
        input: [
          'r',
          '',
        ].join('\n'),
      },
      output: [
        '<kortix_system type="pty-write" source="opencode-pty">',
        'Sent 2 bytes to pty_5c0e9a41: "r\\n"',
        '</kortix_system>',
      ].join('\n'),
      title: 'pty_write',
      metadata: {},
      error: 'Cannot write to PTY \'pty_5c0e9a41\' - session status is \'exited\'.',
      durationMs: 40,
      note: 'Runtime schema is `{ id, data }`, but web and mobile read `input.input || input.text` for the body. `data` alone renders a trigger with no body on BOTH surfaces, so the spec also sets `input` to the same value. Renderer ↔ runtime divergence, not web ↔ mobile.',
    },
    {
      renderer: 'pty-write-tool.tsx',
      tool: 'pty_input',
      input: {
        pty_id: 'pty_5c0e9a41',
        text: [
          'h',
          '',
        ].join('\n'),
      },
      output: [
        '<kortix_system type="pty-write" source="opencode-pty">',
        'Sent 2 bytes to pty_5c0e9a41: "h\\n"',
        '</kortix_system>',
      ].join('\n'),
      title: 'pty_input',
      metadata: {},
      error: 'PTY session \'pty_5c0e9a41\' not found. Use pty_list to see active sessions.',
      durationMs: 35,
      states: ['running', 'completed'],
      note: 'Alias with the alternate field names both renderers accept: `pty_id` for the id and `text` for the input.',
    },
    {
      renderer: 'pty-read-tool.tsx',
      tool: 'pty_read',
      input: {
        id: 'pty_5c0e9a41',
        limit: 200,
      },
      output: [
        '<kortix_system type="pty-output" source="opencode-pty">',
        '<pty_output id="pty_5c0e9a41" status="running">',
        '00001| $ vite',
        '00002| ',
        '00003|   VITE v6.3.5  ready in 412 ms',
        '00004| ',
        '00005|   ➜  press h + enter to show help',
        '00006| 10:42:07 AM [vite] (client) hmr update /src/components/RevenueCard.tsx',
        '00007| 10:42:31 AM [vite] (client) page reload src/pages/Dashboard.tsx',
        '00008| 10:43:02 AM [vite] server restarted.',
        '00009| ',
        '00010|   VITE v6.3.5  ready in 188 ms',
        '',
        '(End of buffer - total 10 lines)',
        '</pty_output>',
        '</kortix_system>',
      ].join('\n'),
      title: 'pty_read',
      metadata: {},
      error: 'PTY session \'pty_5c0e9a41\' not found. Use pty_list to see active sessions.',
      durationMs: 25,
      note: '`<pty_output id status>` with `00001| ` line prefixes and the `(End of buffer …)` footer, as the plugin writes them. Both surfaces strip the prefixes, show a `running` badge, and print the footer under the buffer. The buffer holds no dev-server URL line, because web probes local URLs it finds.',
    },
    {
      renderer: 'pty-kill-tool.tsx',
      tool: 'pty_kill',
      input: {
        id: 'pty_5c0e9a41',
      },
      output: [
        '<kortix_system type="pty-kill" source="opencode-pty">',
        '<pty_killed>',
        'Killed: pty_5c0e9a41 (session retained for log access)',
        'Title: Dev server',
        'Command: bun run dev',
        'Final line count: 10',
        '</pty_killed>',
        '</kortix_system>',
      ].join('\n'),
      title: 'pty_kill',
      metadata: {},
      error: 'Failed to kill PTY session \'pty_5c0e9a41\'.',
      durationMs: 50,
      note: 'Both surfaces run `stripMarkupForToolOutput`, which drops the tags and collapses the four lines into one sentence-like line.',
    },
    // ─── Show ──────────────────────────────────────────────────────────────────
    {
      renderer: 'show-tool.tsx',
      tool: 'show',
      input: {
        action: 'show',
        type: 'markdown',
        title: 'Revenue widget notes',
        path: '/workspace/acme-dashboard/docs/revenue-widget.md',
        content: [
          '# Revenue widget',
          '',
          'The dashboard home shows revenue for the selected range as a card and an area chart.',
          '',
          '## Components',
          '',
          '| Component | File | Purpose |',
          '| --- | --- | --- |',
          '| `RevenueCard` | `src/components/RevenueCard.tsx` | Total and change against the previous period |',
          '| `RevenueChart` | `src/components/RevenueChart.tsx` | Daily revenue as a Recharts area chart |',
          '',
          '## Formatting',
          '',
          '- `formatCurrency(value, { compact: true })` renders `$12.4K` on axes and cards.',
          '- `formatPercent(ratio)` renders a signed change such as `+8.3%`.',
          '',
          '## Next',
          '',
          '1. CSV export of the visible range.',
          '2. Date range presets: 7d, 30d, 90d.',
          '',
        ].join('\n'),
      },
      output: [
        '{',
        '  "success": true,',
        '  "action": "show",',
        '  "entry": {',
        '    "id": "show_1789640000000_k3v9qa",',
        '    "timestamp": "2026-09-17T10:44:12.000Z",',
        '    "type": "markdown",',
        '    "variant": "detail",',
        '    "title": "Revenue widget notes",',
        '    "path": "/workspace/acme-dashboard/docs/revenue-widget.md",',
        '    "content": "# Revenue widget\\n\\nThe dashboard home shows revenue for the selected range as a card and an area chart.\\n\\n## Components\\n\\n| Component | File | Purpose |\\n| --- | --- | --- |\\n| `RevenueCard` | `src/components/RevenueCard.tsx` | Total and change against the previous period |\\n| `RevenueChart` | `src/components/RevenueChart.tsx` | Daily revenue as a Recharts area chart |\\n\\n## Formatting\\n\\n- `formatCurrency(value, { compact: true })` renders `$12.4K` on axes and cards.\\n- `formatPercent(ratio)` renders a signed change such as `+8.3%`.\\n\\n## Next\\n\\n1. CSV export of the visible range.\\n2. Date range presets: 7d, 30d, 90d.\\n"',
        '  },',
        '  "message": "Item \'Revenue widget notes\' presented to user."',
        '}',
      ].join('\n'),
      title: 'show',
      metadata: {},
      error: 'Tool execution aborted',
      durationMs: 20,
      note: 'File show without a byte fetch: `type: markdown` + `path` + inline `content`. `shouldRenderFromSandboxFile` is false (content present), so both surfaces render the markdown branch, and the `path` gives the header its file actions. A bare `type: file` + `path` would fetch the file (web `FileContentRenderer`, mobile `useOpenCodeFileContent`) and degrade to "Preview unavailable" in an offline fixture.',
    },
    {
      renderer: 'show-tool.tsx',
      tool: 'show',
      input: {
        action: 'show',
        type: 'url',
        title: 'Recharts ResponsiveContainer API',
        description: 'Props for the wrapper that sizes the revenue chart to its card.',
        url: 'https://recharts.org/en-US/api/ResponsiveContainer',
      },
      output: [
        '{',
        '  "success": true,',
        '  "action": "show",',
        '  "entry": {',
        '    "id": "show_1789640000000_p8d2xm",',
        '    "timestamp": "2026-09-17T10:44:20.000Z",',
        '    "type": "url",',
        '    "variant": "full",',
        '    "title": "Recharts ResponsiveContainer API",',
        '    "description": "Props for the wrapper that sizes the revenue chart to its card.",',
        '    "url": "https://recharts.org/en-US/api/ResponsiveContainer"',
        '  },',
        '  "message": "Item \'Recharts ResponsiveContainer API\' presented to user."',
        '}',
      ].join('\n'),
      title: 'show',
      metadata: {},
      error: 'Tool execution aborted',
      durationMs: 15,
      note: 'External https URL → link card (title, domain, description) on both surfaces. Web loads the favicon from google.com/s2/favicons inside the renderer; the fixture itself carries no image URL.',
    },
    {
      renderer: 'show-tool.tsx',
      tool: 'show',
      input: {
        action: 'show',
        type: 'markdown',
        title: 'Verification',
        content: [
          '## Revenue widget checks',
          '',
          '| Check | Command | Result |',
          '| --- | --- | --- |',
          '| Typecheck | `bun run typecheck` | Pass |',
          '| Unit tests | `bun test src/lib` | 4 pass, 0 fail |',
          '| Production build | `bun run build` | Pass (first run exited 1: missing `formatPercent`) |',
          '',
          '- `RevenueChart` replaces `LegacyRevenueTable` on the dashboard.',
          '- CSV export and date range presets are next.',
        ].join('\n'),
      },
      output: [
        '{',
        '  "success": true,',
        '  "action": "show",',
        '  "entry": {',
        '    "id": "show_1789640000000_z1c7fe",',
        '    "timestamp": "2026-09-17T10:44:31.000Z",',
        '    "type": "markdown",',
        '    "variant": "detail",',
        '    "title": "Verification",',
        '    "content": "## Revenue widget checks\\n\\n| Check | Command | Result |\\n| --- | --- | --- |\\n| Typecheck | `bun run typecheck` | Pass |\\n| Unit tests | `bun test src/lib` | 4 pass, 0 fail |\\n| Production build | `bun run build` | Pass (first run exited 1: missing `formatPercent`) |\\n\\n- `RevenueChart` replaces `LegacyRevenueTable` on the dashboard.\\n- CSV export and date range presets are next."',
        '  },',
        '  "message": "Item \'Verification\' presented to user."',
        '}',
      ].join('\n'),
      title: 'show',
      metadata: {},
      error: 'Tool execution aborted',
      durationMs: 15,
      note: 'Inline markdown content, no path, no URL. Web adds a header "Preview" button only when a `BoundActivateContext` handler exists and navigation is enabled; mobile computes the same `content-preview` toolbar kind. `show-user` is registered to the same renderer on both surfaces and reads the same fields, so it has no separate spec.',
    },
  ],
};
